import { User, School, Student, Class, Subject, TeacherAssignment, Grade, TrimesterReport, ExamGrade, Employee } from './types';

export const initialData = {
  users: [
    { id: 'u1', name: 'Admin Geral', email: 'admin@escola.com', role: 'admin' as const },
    { id: 'u2', name: 'Sr. Diretor', email: 'diretor@escola.com', role: 'director' as const, schoolId: 's1' },
    { id: 'u3', name: 'Maria Pedagoga', email: 'pedagogico@escola.com', role: 'pedagogical' as const, schoolId: 's1' },
    { id: 'u4', name: 'João Professor', email: 'professor@escola.com', role: 'teacher' as const, schoolId: 's1' },
    { id: 'u5', name: 'Ana Secretaria', email: 'secretaria@escola.com', role: 'secretariat' as const, schoolId: 's1' },
    { id: 'u6', name: 'Ministro da Educação', email: 'ministro@gov.mz', role: 'national' as const },
    { id: 'u7', name: 'Diretor Provincial - Maputo', email: 'provincial@gov.mz', role: 'provincial' as const, provinceId: 'p1' },
    { id: 'u8', name: 'Diretor Distrital - KaMpfumo', email: 'distrital@gov.mz', role: 'district' as const, districtId: 'd1', provinceId: 'p1' },
    { id: 'u9', name: 'Artur Aluno', email: 'aluno@escola.com', role: 'student' as const, studentId: 'stu_1', schoolId: 's1' },
    { id: 'u10', name: 'Beatriz Aluna', email: 'aluno2@escola.com', role: 'student' as const, studentId: 'st02', schoolId: 's1' },
    { id: 'u11', name: 'Diretor Distrital - Matola', email: 'distrital2@gov.mz', role: 'district' as const, districtId: 'd2', provinceId: 'p2' },
    { id: 'u12', name: 'Diretor Provincial - Gaza', email: 'provincial2@gov.mz', role: 'provincial' as const, provinceId: 'p3' },
    { id: 'u13', name: 'Secretário Permanente', email: 'nacional2@gov.mz', role: 'national' as const }
  ],
  provinces: [
    { id: 'p1', name: 'Maputo Cidade' },
    { id: 'p2', name: 'Maputo Província' },
    { id: 'p3', name: 'Gaza' },
    { id: 'p4', name: 'Inhambane' },
    { id: 'p5', name: 'Sofala' }
  ],
  districts: [
    { id: 'd1', name: 'KaMpfumo', provinceId: 'p1' },
    { id: 'd2', name: 'Matola', provinceId: 'p2' },
    { id: 'd3', name: 'Chókwè', provinceId: 'p3' }
  ],
  schools: [
    { id: 's1', name: 'Escola Secundária Central', province: 'Maputo Cidade', district: 'KaMpfumo', address: 'Rua Principal, 123', districtId: 'd1' }
  ],
  classes: [
    { id: 'c_p1', schoolId: 's1', name: 'Turma 1', gradeLevel: '1.ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c_p2', schoolId: 's1', name: 'Turma 1', gradeLevel: '2.ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c_p3', schoolId: 's1', name: 'Turma 1', gradeLevel: '3.ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c_p4', schoolId: 's1', name: 'Turma 1', gradeLevel: '4.ª Classe', year: 2024, period: 'Tarde' },
    { id: 'c_p5', schoolId: 's1', name: 'Turma 1', gradeLevel: '5.ª Classe', year: 2024, period: 'Tarde' },
    { id: 'c_p6', schoolId: 's1', name: 'Turma 1', gradeLevel: '6.ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c_p7', schoolId: 's1', name: 'Turma 1', gradeLevel: '7.ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c_p8', schoolId: 's1', name: 'Turma 1', gradeLevel: '8.ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c_p9', schoolId: 's1', name: 'Turma A', gradeLevel: '9.ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c1', schoolId: 's1', name: 'Turma A', gradeLevel: '10ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c2', schoolId: 's1', name: 'Turma B', gradeLevel: '10ª Classe', year: 2024, period: 'Tarde' },
    { id: 'c3', schoolId: 's1', name: 'Turma C', gradeLevel: '10ª Classe', year: 2024, period: 'Noite' },
    { id: 'c_p11', schoolId: 's1', name: 'Turma A', gradeLevel: '11.ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c_p12', schoolId: 's1', name: 'Turma A', gradeLevel: '12.ª Classe', year: 2024, period: 'Manhã' },
  ],
  students: [
    // -------------------------------------------------------------
    // DIURNO / LABORAL: Turma A (Manhã) - 20 Alunos
    // -------------------------------------------------------------
    { id: 'st01', schoolId: 's1', classId: 'c1', frequencyNumber: 1, name: 'Afonso Matsinhe', gender: 'M', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2007-02-10', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st02', schoolId: 's1', classId: 'c1', frequencyNumber: 2, name: 'Beatriz Silva', gender: 'F', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-08-22', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st03', schoolId: 's1', classId: 'c1', frequencyNumber: 3, name: 'Bernardo Cuamba', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-04-15', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st04', schoolId: 's1', classId: 'c1', frequencyNumber: 4, name: 'Carlos Mendes', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2005-03-15', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st05', schoolId: 's1', classId: 'c1', frequencyNumber: 5, name: 'Celso Mucavel', gender: 'M', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2006-11-20', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st06', schoolId: 's1', classId: 'c1', frequencyNumber: 6, name: 'Daniel Mabote', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-01-12', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st07', schoolId: 's1', classId: 'c1', frequencyNumber: 7, name: 'Domingos Matusse', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-09-05', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st08', schoolId: 's1', classId: 'c1', frequencyNumber: 8, name: 'Eduardo Cossa', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-03-30', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st09', schoolId: 's1', classId: 'c1', frequencyNumber: 9, name: 'Ercília Nhantumbo', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2006-07-14', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st10', schoolId: 's1', classId: 'c1', frequencyNumber: 10, name: 'Fátima Nhaca', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2007-05-18', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st11', schoolId: 's1', classId: 'c1', frequencyNumber: 11, name: 'Filomena Zimba', gender: 'F', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-12-03', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st12', schoolId: 's1', classId: 'c1', frequencyNumber: 12, name: 'Gabriel Sitoe', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-08-25', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st13', schoolId: 's1', classId: 'c1', frequencyNumber: 13, name: 'Gilberto Cuco', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-10-11', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st14', schoolId: 's1', classId: 'c1', frequencyNumber: 14, name: 'Helena Macuácua', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2007-06-29', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st15', schoolId: 's1', classId: 'c1', frequencyNumber: 15, name: 'Hortência Machele', gender: 'F', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-04-19', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st16', schoolId: 's1', classId: 'c1', frequencyNumber: 16, name: 'Inácio Tamele', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-09-08', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st17', schoolId: 's1', classId: 'c1', frequencyNumber: 17, name: 'Ismael Tembe', gender: 'M', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2006-05-23', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st18', schoolId: 's1', classId: 'c1', frequencyNumber: 18, name: 'Jacinto Munguambe', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-11-14', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st19', schoolId: 's1', classId: 'c1', frequencyNumber: 19, name: 'Jorge Mondlane', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-03-02', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st20', schoolId: 's1', classId: 'c1', frequencyNumber: 20, name: 'Kátia Bila', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2007-07-21', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // DIURNO / LABORAL: Turma B (Tarde) - 16 Alunos
    // -------------------------------------------------------------
    { id: 'st21', schoolId: 's1', classId: 'c2', frequencyNumber: 1, name: 'Leonardo Buque', gender: 'M', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2006-02-14', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st22', schoolId: 's1', classId: 'c2', frequencyNumber: 2, name: 'Manuel Chissano', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-03-19', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st23', schoolId: 's1', classId: 'c2', frequencyNumber: 3, name: 'Nilza Cuna', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2006-09-22', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st24', schoolId: 's1', classId: 'c2', frequencyNumber: 4, name: 'Osvaldo Zandamela', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-04-05', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st25', schoolId: 's1', classId: 'c2', frequencyNumber: 5, name: 'Paulo Guambe', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-11-17', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st26', schoolId: 's1', classId: 'c2', frequencyNumber: 6, name: 'Quintino Langa', gender: 'M', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2007-06-01', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st27', schoolId: 's1', classId: 'c2', frequencyNumber: 7, name: 'Rosa Manhiça', gender: 'F', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-08-15', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st28', schoolId: 's1', classId: 'c2', frequencyNumber: 8, name: 'Sérgio Vilanculos', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-01-29', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st29', schoolId: 's1', classId: 'c2', frequencyNumber: 9, name: 'Teresa Tivane', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2006-10-12', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st30', schoolId: 's1', classId: 'c2', frequencyNumber: 10, name: 'Tomás Langa', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2005-12-01', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st31', schoolId: 's1', classId: 'c2', frequencyNumber: 11, name: 'Ussene Saide', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-05-09', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st32', schoolId: 's1', classId: 'c2', frequencyNumber: 12, name: 'Valdemar Mucavele', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-04-26', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st33', schoolId: 's1', classId: 'c2', frequencyNumber: 13, name: 'Wilson Chiconela', gender: 'M', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2007-08-11', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st34', schoolId: 's1', classId: 'c2', frequencyNumber: 14, name: 'Xadreque Machava', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-07-03', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st35', schoolId: 's1', classId: 'c2', frequencyNumber: 15, name: 'Yolanda Macamo', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2007-02-18', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st36', schoolId: 's1', classId: 'c2', frequencyNumber: 16, name: 'Zito Nhamposse', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-12-25', enrollmentDate: '2024-01-12', status: 'active' as const },

    // -------------------------------------------------------------
    // PÓS-LABORAL / NOTURNO: Turma C (Noite) - 10 Alunos
    // Ordem Alfabética Independente de A a Z
    // Contagem de Pauta continua de onde o Laboral terminou
    // -------------------------------------------------------------
    { id: 'st51', schoolId: 's1', classId: 'c3', frequencyNumber: 1, name: 'Abelardo Chirindza', gender: 'M', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2003-05-14', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st52', schoolId: 's1', classId: 'c3', frequencyNumber: 2, name: 'Belmira Muthemba', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2004-09-20', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st53', schoolId: 's1', classId: 'c3', frequencyNumber: 3, name: 'Cassiano Maluleque', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2002-11-08', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st54', schoolId: 's1', classId: 'c3', frequencyNumber: 4, name: 'Dionísio Muchanga', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2003-03-27', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st55', schoolId: 's1', classId: 'c3', frequencyNumber: 5, name: 'Elisa Maposse', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2004-01-19', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st56', schoolId: 's1', classId: 'c3', frequencyNumber: 6, name: 'Fernando Nhatumbo', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2002-08-31', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st57', schoolId: 's1', classId: 'c3', frequencyNumber: 7, name: 'Gracinda Bila', gender: 'F', isNewAdmission: false, entryType: 'continuacao', birthDate: '2003-12-15', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st58', schoolId: 's1', classId: 'c3', frequencyNumber: 8, name: 'Hélder Macamo', gender: 'M', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2004-06-04', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st59', schoolId: 's1', classId: 'c3', frequencyNumber: 9, name: 'Ilda Mondlane', gender: 'F', isNewAdmission: false, entryType: 'continuacao', birthDate: '2002-10-22', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st60', schoolId: 's1', classId: 'c3', frequencyNumber: 10, name: 'Justino Sitoe', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2003-07-11', enrollmentDate: '2024-01-15', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 1.ª CLASSE (Declaração 1º Ciclo Primário - Azul)
    // -------------------------------------------------------------
    { id: 'st_p1_1', schoolId: 's1', classId: 'c_p1', frequencyNumber: 1, name: 'Adilson Fernando Macamo', gender: 'M', fatherName: 'Fernando Macamo', motherName: 'Laura Nhantumbo', isNewAdmission: true, birthDate: '2018-05-14', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p1_2', schoolId: 's1', classId: 'c_p1', frequencyNumber: 2, name: 'Belmira Graça Cossa', gender: 'F', fatherName: 'Estêvão Cossa', motherName: 'Graça Mabunda', isNewAdmission: true, birthDate: '2018-09-22', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 2.ª CLASSE (Declaração 1º Ciclo Primário - Azul)
    // -------------------------------------------------------------
    { id: 'st_p2_1', schoolId: 's1', classId: 'c_p2', frequencyNumber: 1, name: 'Cláudio José Sitoe', gender: 'M', fatherName: 'José Sitoe', motherName: 'Ana Maria Cuna', isNewAdmission: false, birthDate: '2017-02-18', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p2_2', schoolId: 's1', classId: 'c_p2', frequencyNumber: 2, name: 'Dionísia Manuel Langa', gender: 'F', fatherName: 'Manuel Langa', motherName: 'Teresa Tivane', isNewAdmission: false, birthDate: '2017-07-30', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 3.ª CLASSE (Certificado 1º Ciclo Primário)
    // -------------------------------------------------------------
    { id: 'st_p3_1', schoolId: 's1', classId: 'c_p3', frequencyNumber: 1, name: 'Armando Manuel Mabunda', gender: 'M', fatherName: 'Manuel Mabunda', motherName: 'Graça Nhantumbo', isNewAdmission: true, birthDate: '2015-04-12', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p3_2', schoolId: 's1', classId: 'c_p3', frequencyNumber: 2, name: 'Carla Esperança Cossa', gender: 'F', fatherName: 'Estêvão Cossa', motherName: 'Júlia Manhiça', isNewAdmission: false, birthDate: '2015-09-20', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 4.ª CLASSE (Declaração 2º Ciclo Primário - Verde)
    // -------------------------------------------------------------
    { id: 'st_p4_1', schoolId: 's1', classId: 'c_p4', frequencyNumber: 1, name: 'Edilson Samuel Chiconela', gender: 'M', fatherName: 'Samuel Chiconela', motherName: 'Marta Buque', isNewAdmission: false, birthDate: '2014-03-12', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p4_2', schoolId: 's1', classId: 'c_p4', frequencyNumber: 2, name: 'Felisberta João Guambe', gender: 'F', fatherName: 'João Guambe', motherName: 'Rosália Mendes', isNewAdmission: false, birthDate: '2014-08-25', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 5.ª CLASSE (Declaração 2º Ciclo Primário - Verde)
    // -------------------------------------------------------------
    { id: 'st_p5_1', schoolId: 's1', classId: 'c_p5', frequencyNumber: 1, name: 'Gervásio Tomás Nhamposse', gender: 'M', fatherName: 'Tomás Nhamposse', motherName: 'Beatriz Cuamba', isNewAdmission: false, birthDate: '2013-06-19', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p5_2', schoolId: 's1', classId: 'c_p5', frequencyNumber: 2, name: 'Hermínia Paulo Vilanculos', gender: 'F', fatherName: 'Paulo Vilanculos', motherName: 'Elisa Maposse', isNewAdmission: false, birthDate: '2013-10-14', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 6.ª CLASSE (Certificado 2º Ciclo Primário)
    // -------------------------------------------------------------
    { id: 'st_p6_1', schoolId: 's1', classId: 'c_p6', frequencyNumber: 1, name: 'Dário Samuel Chichava', gender: 'M', fatherName: 'Samuel Chichava', motherName: 'Helena Macuácua', isNewAdmission: false, birthDate: '2012-07-15', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p6_2', schoolId: 's1', classId: 'c_p6', frequencyNumber: 2, name: 'Fabiola Teresa Mondlane', gender: 'F', fatherName: 'Tito Mondlane', motherName: 'Margarida Bila', isNewAdmission: false, birthDate: '2012-11-03', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 7.ª CLASSE (Declaração 3º Ciclo Básico - Bordô / Vinho)
    // -------------------------------------------------------------
    { id: 'st_p7_1', schoolId: 's1', classId: 'c_p7', frequencyNumber: 1, name: 'Isac Daniel Muchanga', gender: 'M', fatherName: 'Daniel Muchanga', motherName: 'Nilza Cuna', isNewAdmission: false, birthDate: '2011-01-20', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p7_2', schoolId: 's1', classId: 'c_p7', frequencyNumber: 2, name: 'Joana Carlos Matusse', gender: 'F', fatherName: 'Carlos Matusse', motherName: 'Filomena Zimba', isNewAdmission: false, birthDate: '2011-04-16', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 8.ª CLASSE (Declaração 3º Ciclo Básico - Bordô / Vinho)
    // -------------------------------------------------------------
    { id: 'st_p8_1', schoolId: 's1', classId: 'c_p8', frequencyNumber: 1, name: 'Kílian Vasco Tembe', gender: 'M', fatherName: 'Vasco Tembe', motherName: 'Hortência Machele', isNewAdmission: false, birthDate: '2010-09-08', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p8_2', schoolId: 's1', classId: 'c_p8', frequencyNumber: 2, name: 'Lurdes Bento Mondlane', gender: 'F', fatherName: 'Bento Mondlane', motherName: 'Kátia Bila', isNewAdmission: false, birthDate: '2010-12-05', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 9.ª CLASSE (Certificado Ensino Básico / 1º Ciclo ESG)
    // -------------------------------------------------------------
    { id: 'st_p9_1', schoolId: 's1', classId: 'c_p9', frequencyNumber: 1, name: 'Gerson Lucas Tamele', gender: 'M', fatherName: 'Lucas Tamele', motherName: 'Albertina Cuamba', isNewAdmission: false, birthDate: '2009-03-28', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p9_2', schoolId: 's1', classId: 'c_p9', frequencyNumber: 2, name: 'Ivone Marisa Zandamela', gender: 'F', fatherName: 'Alexandre Zandamela', motherName: 'Zita Langa', isNewAdmission: false, birthDate: '2009-08-19', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 11.ª CLASSE (Declaração 2º Ciclo ESG - Índigo Real)
    // -------------------------------------------------------------
    { id: 'st_p11_1', schoolId: 's1', classId: 'c_p11', frequencyNumber: 1, name: 'Mauro António Nhaca', gender: 'M', fatherName: 'António Nhaca', motherName: 'Fátima Nhaca', isNewAdmission: false, birthDate: '2006-05-11', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p11_2', schoolId: 's1', classId: 'c_p11', frequencyNumber: 2, name: 'Nércia Sebastião Cuco', gender: 'F', fatherName: 'Sebastião Cuco', motherName: 'Ercília Nhantumbo', isNewAdmission: false, birthDate: '2006-10-09', enrollmentDate: '2024-01-10', status: 'active' as const },
  ],
  subjects: [
    { id: 'sub4', name: 'Português', area: 'CS' },
    { id: 'sub5', name: 'Inglês', area: 'CS' },
    { id: 'sub6', name: 'Francês', area: 'CS' },
    { id: 'sub7', name: 'História', area: 'CS' },
    { id: 'sub8', name: 'Geografia', area: 'CS' },
    { id: 'sub1', name: 'Matemática', area: 'MCN' },
    { id: 'sub9', name: 'Biologia', area: 'MCN' },
    { id: 'sub3', name: 'Química', area: 'MCN' },
    { id: 'sub2', name: 'Física', area: 'MCN' },
    { id: 'sub10', name: 'Ed. Visual', area: 'APTP' },
    { id: 'sub11', name: 'Ed. Física', area: 'APTP' },
    { id: 'sub12', name: 'TICs', area: 'APTP' },
    { id: 'sub13', name: 'N. Empre', area: 'APTP' },
    { id: 'sub14', name: 'Agro. Pec.', area: 'APTP' },
  ],
  assignments: [
    { id: 'a1', teacherId: 'u4', classId: 'c1', subjectId: 'sub1' },
    { id: 'a2', teacherId: 'u4', classId: 'c1', subjectId: 'sub2' },
    { id: 'a3', teacherId: 'u4', classId: 'c1', subjectId: 'sub3' },
    { id: 'a4', teacherId: 'u4', classId: 'c1', subjectId: 'sub4' },
    { id: 'a5', teacherId: 'u4', classId: 'c2', subjectId: 'sub1' },
  ],
  grades: (() => {
    const list: Grade[] = [];
    const subs = [
      'sub4', 'sub5', 'sub6', 'sub7', 'sub8', 
      'sub1', 'sub9', 'sub3', 'sub2', 
      'sub10', 'sub11', 'sub12', 'sub13', 'sub14'
    ];

    // Student IDs and their base average
    // Dispensados: st01 (Afonso), st04 (Carlos), st14 (Helena) -> MF >= 14
    // Excluídos: st10 (Fátima), st30 (Tomás Langa) -> MF < 9
    // All others: Admitidos -> MF between 10 and 12
    const studentIds = [
      // Turma A (c1)
      'st01', 'st02', 'st03', 'st04', 'st05', 'st06', 'st07', 'st08', 'st09', 'st10',
      'st11', 'st12', 'st13', 'st14', 'st15', 'st16', 'st17', 'st18', 'st19', 'st20',
      // Turma B (c2)
      'st21', 'st22', 'st23', 'st24', 'st25', 'st26', 'st27', 'st28', 'st29', 'st30',
      'st31', 'st32', 'st33', 'st34', 'st35', 'st36',
      // Turma C (c3 - Pós-Laboral)
      'st51', 'st52', 'st53', 'st54', 'st55', 'st56', 'st57', 'st58', 'st59', 'st60'
    ];

    studentIds.forEach(sId => {
      let baseVal = 11;
      let classId = 'c1';
      if (['st21','st22','st23','st24','st25','st26','st27','st28','st29','st30','st31','st32','st33','st34','st35','st36'].includes(sId)) {
        classId = 'c2';
      } else if (['st51','st52','st53','st54','st55','st56','st57','st58','st59','st60'].includes(sId)) {
        classId = 'c3';
      }

      if (['st01', 'st04', 'st14'].includes(sId)) {
        baseVal = 15; // Dispensado
      } else if (['st10', 'st30'].includes(sId)) {
        baseVal = 7; // Excluído
      } else {
        baseVal = 10 + (parseInt(sId.replace('st', ''), 10) % 3); // 10, 11, or 12 -> Admitido
      }

      subs.forEach((subId, subIdx) => {
        const offset = (subIdx % 3) - 1;
        const val = Math.max(5, Math.min(19, baseVal + offset));
        
        // Trimester 1
        list.push({
          id: `g-${sId}-${subId}-t1`,
          studentId: sId,
          classId,
          subjectId: subId,
          teacherId: 'u4',
          trimester: 1,
          acs1: val,
          acs2: val,
          acs3: val,
          apt: val,
          media: val,
          isLocked: true
        });

        // Trimester 2
        list.push({
          id: `g-${sId}-${subId}-t2`,
          studentId: sId,
          classId,
          subjectId: subId,
          teacherId: 'u4',
          trimester: 2,
          acs1: val,
          acs2: val,
          acs3: val,
          apt: val,
          media: val,
          isLocked: true
        });

        // Trimester 3
        list.push({
          id: `g-${sId}-${subId}-t3`,
          studentId: sId,
          classId,
          subjectId: subId,
          teacherId: 'u4',
          trimester: 3,
          acs1: val,
          acs2: val,
          acs3: val,
          apt: val,
          media: val,
          isLocked: true
        });
      });
    });

    return list;
  })(),
  examGrades: [] as ExamGrade[],
  reports: [] as TrimesterReport[],
  employees: [
    {
      id: 'CAL-102938475',
      schoolId: 's1',
      name: 'Carlos Alberto Langa',
      gender: 'M',
      nuit: '102938475',
      email: 'carlos.langa@mined.gov.mz',
      phone: '+258 84 391 8294',
      maritalStatus: 'Casado',
      fatherName: 'Alberto Langa',
      motherName: 'Maria Chissano Langa',
      idCardNumber: '110100482910M',
      idCardIssuedAt: 'Matola',
      idCardIssuedDate: '2018-04-12',
      nationality: 'Moçambicana',
      birthProvince: 'Maputo Província',
      birthDistrict: 'Matola (Cidade)',
      birthDate: '1982-05-14',
      address: 'Bairro da Liberdade, Rua 12, Casa 45',
      neighborhood: 'Liberdade',
      residenceDistrict: 'Matola (Cidade)',
      cell: 'B',
      blockNo: '14',
      houseNo: '45',
      childrenCount: 3,
      career: 'Docente',
      category: 'Docente N1',
      roleFunction: 'Professor de Matemática e Delegado de Disciplina',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2010-02-01',
      academicLevel: 'Licenciatura',
      trainingArea: 'Ensino de Matemática',
      leadershipRole: 'Delegado de Disciplina',
      taughtSubjects: ['Matemática']
    },
    {
      id: 'ABM-201948392',
      schoolId: 's1',
      name: 'Ana Beatriz Machava',
      gender: 'F',
      nuit: '201948392',
      email: 'ana.machava@mined.gov.mz',
      phone: '+258 82 918 2741',
      maritalStatus: 'Solteiro',
      fatherName: 'Beatriz Machava Pai',
      motherName: 'Rosa Tembe Machava',
      idCardNumber: '110200847291F',
      idCardIssuedAt: 'Chókwè',
      idCardIssuedDate: '2019-09-20',
      nationality: 'Moçambicana',
      birthProvince: 'Gaza',
      birthDistrict: 'Chókwè',
      birthDate: '1979-11-20',
      address: 'Av. Eduardo Mondlane, Q. 8',
      neighborhood: 'Central',
      residenceDistrict: 'Maputo Cidade',
      cell: 'A',
      blockNo: '08',
      houseNo: '12',
      childrenCount: 2,
      career: 'CTA',
      category: 'Técnico Superior N1',
      roleFunction: 'Chefe da Secretaria Geral',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2008-06-15',
      academicLevel: 'Licenciatura',
      trainingArea: 'Administração Pública e Gestão de RH',
      leadershipRole: 'Chefe de Secretaria',
      taughtSubjects: []
    },
    {
      id: 'TEC-309482716',
      schoolId: 's1',
      name: 'Tomás Estêvão Cossa',
      gender: 'M',
      nuit: '309482716',
      email: 'tomas.cossa@mined.gov.mz',
      phone: '+258 87 501 9283',
      maritalStatus: 'Casado',
      fatherName: 'Estêvão Cossa',
      motherName: 'Margarida Sitoe Cossa',
      idCardNumber: '110300192847T',
      idCardIssuedAt: 'Beira',
      idCardIssuedDate: '2017-03-10',
      nationality: 'Moçambicana',
      birthProvince: 'Sofala',
      birthDistrict: 'Beira (Cidade)',
      birthDate: '1985-08-09',
      address: 'Bairro Ponta Gêa, Rua 4',
      neighborhood: 'Ponta Gêa',
      residenceDistrict: 'Beira (Cidade)',
      cell: 'C',
      blockNo: '22',
      houseNo: '10',
      childrenCount: 2,
      career: 'Docente',
      category: 'Docente N1',
      roleFunction: 'Director Adjunto Pedagógico',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2012-01-15',
      academicLevel: 'Mestrado',
      trainingArea: 'Gestão Educacional e Física',
      leadershipRole: 'Director Adjunto Pedagógico',
      taughtSubjects: ['Física']
    },
    {
      id: 'MHM-401928374',
      schoolId: 's1',
      name: 'Maria Helena Mabunda',
      gender: 'F',
      nuit: '401928374',
      email: 'maria.mabunda@mined.gov.mz',
      phone: '+258 84 990 1284',
      maritalStatus: 'Casado',
      fatherName: 'Helena Mabunda',
      motherName: 'Joana Guambe',
      idCardNumber: '110400582910H',
      idCardIssuedAt: 'Maxixe',
      idCardIssuedDate: '2020-01-18',
      nationality: 'Moçambicana',
      birthProvince: 'Inhambane',
      birthDistrict: 'Maxixe (Cidade)',
      birthDate: '1990-03-27',
      address: 'Bairro Chambone, Rua 3',
      neighborhood: 'Chambone',
      residenceDistrict: 'Maxixe (Cidade)',
      cell: 'A',
      blockNo: '05',
      houseNo: '18',
      childrenCount: 1,
      career: 'Docente',
      category: 'Docente N2',
      roleFunction: 'Professora de Língua Portuguesa',
      isEffective: 'Não',
      contractType: 'Contrato a Termo Certo',
      contractLink: 'Contratado do Estado',
      admissionDate: '2021-02-01',
      academicLevel: 'Licenciatura',
      trainingArea: 'Ensino de Língua Portuguesa',
      leadershipRole: 'Directora de Turma',
      taughtSubjects: ['Português']
    },
    // Mais Docentes
    {
      id: 'ASM-501928471',
      schoolId: 's1',
      name: 'Arlindo Sérgio Macuácua',
      gender: 'M',
      nuit: '501928471',
      email: 'arlindo.macuacua@mined.gov.mz',
      phone: '+258 84 210 3948',
      maritalStatus: 'Casado',
      fatherName: 'Sérgio Macuácua',
      motherName: 'Emília Chissano',
      idCardNumber: '110500392810K',
      idCardIssuedAt: 'Xai-Xai',
      idCardIssuedDate: '2016-05-14',
      nationality: 'Moçambicana',
      birthProvince: 'Gaza',
      birthDistrict: 'Xai-Xai',
      birthDate: '1984-11-19',
      address: 'Bairro 2, Casa 15',
      neighborhood: 'Marien Ngouabi',
      residenceDistrict: 'Xai-Xai',
      cell: 'B',
      blockNo: '04',
      houseNo: '15',
      childrenCount: 2,
      career: 'Docente',
      category: 'Docente N1',
      roleFunction: 'Professor de Química',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2011-03-01',
      academicLevel: 'Licenciatura',
      trainingArea: 'Ensino de Química e Biologia',
      leadershipRole: 'Delegado de Disciplina',
      taughtSubjects: ['Química']
    },
    {
      id: 'JAS-601928582',
      schoolId: 's1',
      name: 'Joana Amélia Sitoe',
      gender: 'F',
      nuit: '601928582',
      email: 'joana.sitoe@mined.gov.mz',
      phone: '+258 82 490 1827',
      maritalStatus: 'Casado',
      fatherName: 'Américo Sitoe',
      motherName: 'Teresa Langa Sitoe',
      idCardNumber: '110600492811L',
      idCardIssuedAt: 'Maputo',
      idCardIssuedDate: '2015-11-20',
      nationality: 'Moçambicana',
      birthProvince: 'Maputo Cidade',
      birthDistrict: 'KaMpfumo',
      birthDate: '1983-04-12',
      address: 'Bairro da Malhangalene, Rua 5',
      neighborhood: 'Malhangalene',
      residenceDistrict: 'Maputo Cidade',
      cell: 'A',
      blockNo: '12',
      houseNo: '44',
      childrenCount: 3,
      career: 'Docente',
      category: 'Docente N1',
      roleFunction: 'Professora de Biologia',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2009-08-01',
      academicLevel: 'Mestrado',
      trainingArea: 'Ciências Biológicas e Didáctica',
      leadershipRole: 'Directora de Turma',
      taughtSubjects: ['Biologia']
    },
    {
      id: 'FZT-701928693',
      schoolId: 's1',
      name: 'Feliciano Zacarias Tembe',
      gender: 'M',
      nuit: '701928693',
      email: 'feliciano.tembe@mined.gov.mz',
      phone: '+258 87 392 0192',
      maritalStatus: 'Solteiro',
      fatherName: 'Zacarias Tembe',
      motherName: 'Júlia Vilanculos',
      idCardNumber: '110700592812M',
      idCardIssuedAt: 'Inhambane',
      idCardIssuedDate: '2019-02-15',
      nationality: 'Moçambicana',
      birthProvince: 'Inhambane',
      birthDistrict: 'Homoíne',
      birthDate: '1988-09-05',
      address: 'Bairro Liberdade, Rua 8',
      neighborhood: 'Liberdade',
      residenceDistrict: 'Matola',
      cell: 'D',
      blockNo: '18',
      houseNo: '23',
      childrenCount: 0,
      career: 'Docente',
      category: 'Docente N2',
      roleFunction: 'Professor de História',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2018-02-01',
      academicLevel: 'Licenciatura',
      trainingArea: 'Ensino de História de Moçambique e Geral',
      leadershipRole: 'Delegado de Disciplina',
      taughtSubjects: ['História']
    },
    {
      id: 'LEM-801928704',
      schoolId: 's1',
      name: 'Lurdes Ernesto Mondlane',
      gender: 'F',
      nuit: '801928704',
      email: 'lurdes.mondlane@mined.gov.mz',
      phone: '+258 84 582 9102',
      maritalStatus: 'Casado',
      fatherName: 'Ernesto Mondlane',
      motherName: 'Graça Nhaca',
      idCardNumber: '110800692813N',
      idCardIssuedAt: 'Chibuto',
      idCardIssuedDate: '2017-08-22',
      nationality: 'Moçambicana',
      birthProvince: 'Gaza',
      birthDistrict: 'Chibuto',
      birthDate: '1987-12-03',
      address: 'Bairro Central, Av. 24 de Julho',
      neighborhood: 'Central',
      residenceDistrict: 'Maputo Cidade',
      cell: 'B',
      blockNo: '06',
      houseNo: '19',
      childrenCount: 2,
      career: 'Docente',
      category: 'Docente N1',
      roleFunction: 'Professora de Geografia',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2014-04-15',
      academicLevel: 'Licenciatura',
      trainingArea: 'Geografia e Planeamento Físico',
      leadershipRole: 'Directora de Turma',
      taughtSubjects: ['Geografia']
    },
    {
      id: 'SPC-901928815',
      schoolId: 's1',
      name: 'Samuel Paulo Chissano',
      gender: 'M',
      nuit: '901928815',
      email: 'samuel.chissano@mined.gov.mz',
      phone: '+258 86 492 8172',
      maritalStatus: 'Solteiro',
      fatherName: 'Paulo Chissano',
      motherName: 'Marta Buque',
      idCardNumber: '110900792814P',
      idCardIssuedAt: 'Nampula',
      idCardIssuedDate: '2021-04-10',
      nationality: 'Moçambicana',
      birthProvince: 'Nampula',
      birthDistrict: 'Nampula (Cidade)',
      birthDate: '1992-06-18',
      address: 'Bairro Muatala, Rua Principal',
      neighborhood: 'Muatala',
      residenceDistrict: 'Nampula (Cidade)',
      cell: 'C',
      blockNo: '11',
      houseNo: '07',
      childrenCount: 1,
      career: 'Docente',
      category: 'Docente N2',
      roleFunction: 'Professor de Língua Inglesa',
      isEffective: 'Não',
      contractType: 'Contrato a Termo Certo',
      contractLink: 'Contratado do Estado',
      admissionDate: '2022-02-01',
      academicLevel: 'Licenciatura',
      trainingArea: 'Ensino de Língua Inglesa',
      leadershipRole: 'Docente',
      taughtSubjects: ['Inglês']
    },
    {
      id: 'BXN-101928926',
      schoolId: 's1',
      name: 'Bento Xavier Nhamposse',
      gender: 'M',
      nuit: '101928926',
      email: 'bento.nhamposse@mined.gov.mz',
      phone: '+258 82 710 4928',
      maritalStatus: 'Casado',
      fatherName: 'Xavier Nhamposse',
      motherName: 'Flora Bila',
      idCardNumber: '111000892815Q',
      idCardIssuedAt: 'Maputo',
      idCardIssuedDate: '2014-07-30',
      nationality: 'Moçambicana',
      birthProvince: 'Maputo Província',
      birthDistrict: 'Boane',
      birthDate: '1981-01-25',
      address: 'Vila de Boane, Rua 3',
      neighborhood: 'Boane Sede',
      residenceDistrict: 'Boane',
      cell: 'A',
      blockNo: '02',
      houseNo: '55',
      childrenCount: 4,
      career: 'Docente',
      category: 'Docente N3',
      roleFunction: 'Professor de Educação Física',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2006-03-01',
      academicLevel: 'Médio',
      trainingArea: 'Educação Física e Desporto Escolar',
      leadershipRole: 'Responsável do Desporto Escolar',
      taughtSubjects: ['Ed. Física']
    },
    // Mais CTA (Corpo Técnico-Administrativo)
    {
      id: 'ESG-201928037',
      schoolId: 's1',
      name: 'Ernesto Salvador Guambe',
      gender: 'M',
      nuit: '201928037',
      email: 'ernesto.guambe@mined.gov.mz',
      phone: '+258 84 928 3741',
      maritalStatus: 'Casado',
      fatherName: 'Salvador Guambe',
      motherName: 'Anita Cossa',
      idCardNumber: '111100992816R',
      idCardIssuedAt: 'Maputo',
      idCardIssuedDate: '2016-10-18',
      nationality: 'Moçambicana',
      birthProvince: 'Maputo Província',
      birthDistrict: 'Manhiça',
      birthDate: '1980-03-14',
      address: 'Bairro Fomento, Rua das Flores',
      neighborhood: 'Fomento',
      residenceDistrict: 'Matola',
      cell: 'B',
      blockNo: '09',
      houseNo: '31',
      childrenCount: 3,
      career: 'CTA',
      category: 'Técnico Superior N1',
      roleFunction: 'Responsável de Finanças e Tesouraria',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2010-09-01',
      academicLevel: 'Licenciatura',
      trainingArea: 'Contabilidade e Auditoria Pública',
      leadershipRole: 'Tesoureiro',
      taughtSubjects: []
    },
    {
      id: 'MPM-301928148',
      schoolId: 's1',
      name: 'Marta Paulino Matsinhe',
      gender: 'F',
      nuit: '301928148',
      email: 'marta.matsinhe@mined.gov.mz',
      phone: '+258 82 301 9284',
      maritalStatus: 'Solteiro',
      fatherName: 'Paulino Matsinhe',
      motherName: 'Leonor Cuamba',
      idCardNumber: '111200092817S',
      idCardIssuedAt: 'Chókwè',
      idCardIssuedDate: '2018-06-12',
      nationality: 'Moçambicana',
      birthProvince: 'Gaza',
      birthDistrict: 'Guijá',
      birthDate: '1986-10-29',
      address: 'Bairro Machava-Socimol, Rua 7',
      neighborhood: 'Machava',
      residenceDistrict: 'Matola',
      cell: 'A',
      blockNo: '14',
      houseNo: '28',
      childrenCount: 1,
      career: 'CTA',
      category: 'Técnico Profissional',
      roleFunction: 'Oficial de Matrículas e Processos Individuais',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2013-05-15',
      academicLevel: 'Médio',
      trainingArea: 'Administração e Gestão de Documentos',
      leadershipRole: 'Secretaria',
      taughtSubjects: []
    },
    {
      id: 'ASC-401928259',
      schoolId: 's1',
      name: 'Alberto Salomão Cuamba',
      gender: 'M',
      nuit: '401928259',
      email: 'alberto.cuamba@mined.gov.mz',
      phone: '+258 87 192 8374',
      maritalStatus: 'Casado',
      fatherName: 'Salomão Cuamba',
      motherName: 'Elisa Zandamela',
      idCardNumber: '111300192818T',
      idCardIssuedAt: 'Quelimane',
      idCardIssuedDate: '2015-09-04',
      nationality: 'Moçambicana',
      birthProvince: 'Zambézia',
      birthDistrict: 'Quelimane',
      birthDate: '1978-07-22',
      address: 'Bairro Central, Av. Maguiguana',
      neighborhood: 'Central',
      residenceDistrict: 'Maputo Cidade',
      cell: 'C',
      blockNo: '03',
      houseNo: '10',
      childrenCount: 2,
      career: 'CTA',
      category: 'Técnico Superior N2',
      roleFunction: 'Bibliotecário Chefe e Gestor do Centro de Recursos',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2011-01-20',
      academicLevel: 'Licenciatura',
      trainingArea: 'Ciências de Informação e Biblioteconomia',
      leadershipRole: 'Bibliotecário Chefe',
      taughtSubjects: []
    },
    {
      id: 'JVZ-501928360',
      schoolId: 's1',
      name: 'Jaime Valente Zandamela',
      gender: 'M',
      nuit: '501928360',
      email: 'jaime.zandamela@mined.gov.mz',
      phone: '+258 84 719 2831',
      maritalStatus: 'Solteiro',
      fatherName: 'Valente Zandamela',
      motherName: 'Constância Sitoe',
      idCardNumber: '111400292819U',
      idCardIssuedAt: 'Matola',
      idCardIssuedDate: '2022-03-15',
      nationality: 'Moçambicana',
      birthProvince: 'Maputo Província',
      birthDistrict: 'Matola',
      birthDate: '1995-12-08',
      address: 'Bairro Trevo, Rua 2',
      neighborhood: 'Trevo',
      residenceDistrict: 'Matola',
      cell: 'D',
      blockNo: '08',
      houseNo: '14',
      childrenCount: 0,
      career: 'CTA',
      category: 'Técnico de Informática',
      roleFunction: 'Administrador de Rede e Suporte Tecnológico',
      isEffective: 'Não',
      contractType: 'Contrato a Termo Certo',
      contractLink: 'Contratado do Estado',
      admissionDate: '2023-01-10',
      academicLevel: 'Médio',
      trainingArea: 'Técnico de Informática e Redes de Computadores',
      leadershipRole: 'Suporte TIC',
      taughtSubjects: []
    },
    {
      id: 'PFL-601928471',
      schoolId: 's1',
      name: 'Pedro Fernando Langa',
      gender: 'M',
      nuit: '601928471',
      email: 'pedro.langa@mined.gov.mz',
      phone: '+258 82 829 1047',
      maritalStatus: 'Casado',
      fatherName: 'Fernando Langa',
      motherName: 'Belmira Cossa',
      idCardNumber: '111500392820V',
      idCardIssuedAt: 'Chókwè',
      idCardIssuedDate: '2012-08-19',
      nationality: 'Moçambicana',
      birthProvince: 'Gaza',
      birthDistrict: 'Chókwè',
      birthDate: '1975-04-16',
      address: 'Bairro T3, Rua 11',
      neighborhood: 'T3',
      residenceDistrict: 'Matola',
      cell: 'B',
      blockNo: '21',
      houseNo: '88',
      childrenCount: 5,
      career: 'CTA',
      category: 'Agente de Serviço e Segurança',
      roleFunction: 'Encarregado de Portaria e Segurança Patrimonial',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2005-02-15',
      academicLevel: 'Básico',
      trainingArea: 'Segurança e Vigilância Física',
      leadershipRole: 'Chefe de Segurança',
      taughtSubjects: []
    },
    {
      id: 'RDN-701928582',
      schoolId: 's1',
      name: 'Rosa Dulce Nhantumbo',
      gender: 'F',
      nuit: '701928582',
      email: 'rosa.nhantumbo@mined.gov.mz',
      phone: '+258 86 501 9283',
      maritalStatus: 'Viúvo',
      fatherName: 'Dulce Nhantumbo',
      motherName: 'Albertina Tembe',
      idCardNumber: '111600492821W',
      idCardIssuedAt: 'Maputo',
      idCardIssuedDate: '2013-04-25',
      nationality: 'Moçambicana',
      birthProvince: 'Maputo Província',
      birthDistrict: 'Marracuene',
      birthDate: '1977-08-30',
      address: 'Bairro Zimpeto, Rua das Acácias',
      neighborhood: 'Zimpeto',
      residenceDistrict: 'Maputo Cidade',
      cell: 'A',
      blockNo: '05',
      houseNo: '16',
      childrenCount: 3,
      career: 'CTA',
      category: 'Auxiliar Administrativo',
      roleFunction: 'Encarregada de Higiene e Manutenção das Instalações',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2007-07-01',
      academicLevel: 'Básico',
      trainingArea: 'Higiene e Sanitação Escolar',
      leadershipRole: 'Encarregada de Limpeza',
      taughtSubjects: []
    }
  ] as Employee[],
  collectionPeriods: [
    {
      id: 'period-1',
      title: 'Recolha Estatística Trimestral - Q1 2026',
      description: 'Recolha obrigatória de dados de aproveitamento e efetivo escolar.',
      startDate: '2026-03-20',
      endDate: '2026-03-31',
      status: 'published',
      createdByRole: 'national',
      targetLevel: 'school',
      createdAt: '2026-03-01T10:00:00Z'
    }
  ],
  collectionForms: [],
  transferRequests: [],
  academicComplaints: [],
  chatMessages: [
    {
      id: 'msg-1',
      senderId: 'u6',
      senderName: 'Ministro da Educação',
      senderRole: 'national',
      receiverLevel: 'provincial',
      text: 'Bem-vindos ao novo sistema de coordenação nacional.',
      timestamp: '2026-03-01T11:00:00Z'
    }
  ],
};
