import { User, School, Student, Class, Subject, TeacherAssignment, Grade, TrimesterReport, ExamGrade, Employee } from './types';

export const initialData = {
  users: [
    { id: 'u1', name: 'Admin Geral', email: 'admin@escola.com', role: 'admin' as const },
    { id: 'u2', name: 'Dr. Manuel Mabote', email: 'diretor@escola.com', role: 'director' as const, schoolId: 's1' },
    { id: 'u3', name: 'Dra. Maria Pedagoga', email: 'pedagogico@escola.com', role: 'pedagogical' as const, schoolId: 's1' },
    { id: 'u4', name: 'Prof. João Professor', email: 'professor@escola.com', role: 'teacher' as const, schoolId: 's1' },
    { id: 'u5', name: 'Dra. Ana Secretaria', email: 'secretaria@escola.com', role: 'secretariat' as const, schoolId: 's1' },
    { id: 'u5_rh', name: 'Dra. Fátima Cossa', email: 'rh@escola.com', role: 'secretariat_rh' as const, schoolId: 's1', department: 'Recursos Humanos' },
    { id: 'u5_pat', name: 'Eng. Alberto Sithole', email: 'patrimonio@escola.com', role: 'secretariat_patrimonio' as const, schoolId: 's1', department: 'Património e Logística' },
    { id: 'u5_rec', name: 'Sra. Laura Nhantumbo', email: 'recepcao@escola.com', role: 'secretariat_recepcao' as const, schoolId: 's1', department: 'Atendimento e Recepção' },
    { id: 'u5_arq', name: 'Sr. Tomás Cossa', email: 'arquivo@escola.com', role: 'secretariat_arquivo' as const, schoolId: 's1', department: 'Arquivo Geral' },
    { id: 'u5_fin', name: 'Dr. Paulo Guambe', email: 'financas@escola.com', role: 'secretariat_financas' as const, schoolId: 's1', department: 'Tesouraria e Finanças' },
    { id: 'u14', name: 'Dra. Teresa Tivane', email: 'biblioteca@escola.com', role: 'librarian' as const, schoolId: 's1', department: 'Biblioteca Escolar' },
    { id: 'u15', name: 'Sr. Fernando Macamo', email: 'encarregado@escola.com', role: 'guardian' as const, schoolId: 's1', guardianStudentIds: ['st01', 'st02'] },
    { id: 'u6', name: 'Ministro da Educação', email: 'ministro@gov.mz', role: 'national' as const },
    { id: 'u7', name: 'Diretor Provincial - Maputo', email: 'provincial@gov.mz', role: 'provincial' as const, provinceId: 'p1' },
    { id: 'u8', name: 'Diretor Distrital - KaMpfumo', email: 'distrital@gov.mz', role: 'district' as const, districtId: 'd1', provinceId: 'p1' },
    { id: 'u9', name: 'Artur Aluno', email: 'aluno@escola.com', role: 'student' as const, studentId: 'st01', schoolId: 's1' },
    { id: 'u10', name: 'Beatriz Aluna', email: 'aluno2@escola.com', role: 'student' as const, studentId: 'st02', schoolId: 's1' },
    { id: 'u11', name: 'Diretor Distrital - Matola', email: 'distrital2@gov.mz', role: 'district' as const, districtId: 'd2', provinceId: 'p2' },
    { id: 'u12', name: 'Diretor Provincial - Gaza', email: 'provincial2@gov.mz', role: 'provincial' as const, provinceId: 'p3' },
    { id: 'u13', name: 'Secretário Permanente', email: 'nacional2@gov.mz', role: 'national' as const }
  ],
  provinces: [
    { id: 'p1', name: 'Maputo Cidade' },
    { id: 'p2', name: 'Maputo Província' },
    { id: 'p3', name: 'Gaza' },
    { id: 'p4', name: 'Inhambane' },
    { id: 'p5', name: 'Sofala' }
  ],
  districts: [
    { id: 'd1', name: 'KaMpfumo', provinceId: 'p1' },
    { id: 'd2', name: 'Matola', provinceId: 'p2' },
    { id: 'd3', name: 'Chókwè', provinceId: 'p3' }
  ],
  schools: [
    { 
      id: 's1', 
      name: 'Escola Secundária Josina Machel', 
      code: 'ESC-MAP-001',
      logoUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&q=80&w=200',
      managementType: 'estatal',
      province: 'Maputo Cidade', 
      district: 'KaMpfumo', 
      locality: 'Urbanização',
      administrativePost: 'Urbanização',
      address: 'Av. Mao Tse Tung, nº 1420', 
      districtId: 'd1',
      schoolTypes: ['ENSINO SECUNDÁRIO DO 1 CICLO', 'ENSINO SECUNDÁRIO DO 2 CICLO', 'ENSINO PRÉ-UNIVERSITÁRIO'],
      directorName: 'Dr. Manuel Mabote',
      dapName: 'Dra. Maria Pedagoga',
      secretariatChiefName: 'Dra. Ana Secretaria',
      phone: '+258 84 123 4567',
      email: 'secretaria.josinamachel@minedh.gov.mz',
      shifts: ['Diurno', 'Nocturno'],
      studentCapacity: 3500,
      autoAssignedClasses: ['7.ª Classe', '8.ª Classe', '9.ª Classe', '10.ª Classe', '11.ª Classe', '12.ª Classe'],
      autoAssignedSubjects: ['Português', 'Matemática', 'Física', 'Química', 'Biologia', 'História', 'Geografia', 'Inglês', 'Francês', 'Filosofia', 'TIC / Informática']
    },
    { 
      id: 's2', 
      name: 'Escola Primária Completa Unidade 7', 
      code: 'EPC-MAP-042',
      logoUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&q=80&w=200',
      managementType: 'estatal',
      province: 'Maputo Cidade', 
      district: 'Nlhamankulu', 
      locality: 'Malangalene',
      administrativePost: 'Malangalene A',
      address: 'Bairro Chamanculo B', 
      districtId: 'd1',
      schoolTypes: ['EP1', 'EP2', 'ENSINO BÁSICO'],
      directorName: 'Profa. Sofia Langa',
      dapName: 'Prof. Carlos Nhavoto',
      secretariatChiefName: 'Sr. Ernesto Macamo',
      phone: '+258 82 987 6543',
      email: 'epc.unidade7@minedh.gov.mz',
      shifts: ['Diurno'],
      studentCapacity: 1800,
      autoAssignedClasses: ['1.ª Classe', '2.ª Classe', '3.ª Classe', '4.ª Classe', '5.ª Classe', '6.ª Classe', '7.ª Classe', '8.ª Classe', '9.ª Classe'],
      autoAssignedSubjects: ['Português', 'Matemática', 'Ciências Naturais', 'História', 'Geografia', 'Educação Física', 'Inglês']
    },
    { 
      id: 's3', 
      name: 'Instituto Técnico Profissional da Matola', 
      code: 'ITP-MAT-108',
      logoUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=200',
      managementType: 'privado',
      province: 'Maputo Província', 
      district: 'Matola', 
      locality: 'Fomento',
      administrativePost: 'Matola Sede',
      address: 'Av. das Indústrias, Km 4', 
      districtId: 'd2',
      schoolTypes: ['ENSINO TÉCNICO PROFISSIONAL', 'ENSINO MÉDIO PROFISSIONAL'],
      directorName: 'Eng. Tomas Mondlane',
      dapName: 'Msc. Alberto Sithole',
      secretariatChiefName: 'Sra. Teresa Tembe',
      phone: '+258 87 555 1212',
      email: 'contacto@itpmatola.ac.mz',
      shifts: ['Diurno', 'Nocturno'],
      studentCapacity: 1200,
      autoAssignedClasses: ['Nível 3 Técnico', 'Nível 4 Técnico', 'Nível 5 Técnico', '1º Ano Médio', '2º Ano Médio', '3º Ano Médio'],
      autoAssignedSubjects: ['Português Aplicado', 'Matemática Financeira', 'Desenho Técnico', 'TIC / Informática', 'Gestão e Empreendedorismo', 'Módulos Vocacionais Práticos']
    }
  ],
  classes: [
    { id: 'c_p1', schoolId: 's1', name: 'Turma 1', gradeLevel: '1.ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c_p2', schoolId: 's1', name: 'Turma 1', gradeLevel: '2.ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c_p3', schoolId: 's1', name: 'Turma 1', gradeLevel: '3.ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c_p4', schoolId: 's1', name: 'Turma 1', gradeLevel: '4.ª Classe', year: 2024, period: 'Tarde' },
    { id: 'c_p5', schoolId: 's1', name: 'Turma 1', gradeLevel: '5.ª Classe', year: 2024, period: 'Tarde' },
    { id: 'c_p6', schoolId: 's1', name: 'Turma 1', gradeLevel: '6.ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c_p7', schoolId: 's1', name: 'Turma 1', gradeLevel: '7.ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c_p8', schoolId: 's1', name: 'Turma 1', gradeLevel: '8.ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c_p9', schoolId: 's1', name: 'Turma A', gradeLevel: '9.ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c1', schoolId: 's1', name: 'Turma A', gradeLevel: '10ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c2', schoolId: 's1', name: 'Turma B', gradeLevel: '10ª Classe', year: 2024, period: 'Tarde' },
    { id: 'c3', schoolId: 's1', name: 'Turma C', gradeLevel: '10ª Classe', year: 2024, period: 'Noite' },
    { id: 'c_p11', schoolId: 's1', name: 'Turma A', gradeLevel: '11.ª Classe', year: 2024, period: 'Manhã' },
    { id: 'c_p12', schoolId: 's1', name: 'Turma A', gradeLevel: '12.ª Classe', year: 2024, period: 'Manhã' },
  ],
  students: [
    // -------------------------------------------------------------
    // DIURNO / LABORAL: Turma A (Manhã) - 20 Alunos
    // -------------------------------------------------------------
    { id: 'st01', schoolId: 's1', classId: 'c1', frequencyNumber: 1, name: 'Afonso Matsinhe', gender: 'M', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2007-02-10', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st02', schoolId: 's1', classId: 'c1', frequencyNumber: 2, name: 'Beatriz Silva', gender: 'F', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-08-22', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st03', schoolId: 's1', classId: 'c1', frequencyNumber: 3, name: 'Bernardo Cuamba', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-04-15', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st04', schoolId: 's1', classId: 'c1', frequencyNumber: 4, name: 'Carlos Mendes', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2005-03-15', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st05', schoolId: 's1', classId: 'c1', frequencyNumber: 5, name: 'Celso Mucavel', gender: 'M', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2006-11-20', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st06', schoolId: 's1', classId: 'c1', frequencyNumber: 6, name: 'Daniel Mabote', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-01-12', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st07', schoolId: 's1', classId: 'c1', frequencyNumber: 7, name: 'Domingos Matusse', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-09-05', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st08', schoolId: 's1', classId: 'c1', frequencyNumber: 8, name: 'Eduardo Cossa', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-03-30', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st09', schoolId: 's1', classId: 'c1', frequencyNumber: 9, name: 'Ercília Nhantumbo', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2006-07-14', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st10', schoolId: 's1', classId: 'c1', frequencyNumber: 10, name: 'Fátima Nhaca', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2007-05-18', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st11', schoolId: 's1', classId: 'c1', frequencyNumber: 11, name: 'Filomena Zimba', gender: 'F', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-12-03', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st12', schoolId: 's1', classId: 'c1', frequencyNumber: 12, name: 'Gabriel Sitoe', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-08-25', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st13', schoolId: 's1', classId: 'c1', frequencyNumber: 13, name: 'Gilberto Cuco', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-10-11', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st14', schoolId: 's1', classId: 'c1', frequencyNumber: 14, name: 'Helena Macuácua', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2007-06-29', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st15', schoolId: 's1', classId: 'c1', frequencyNumber: 15, name: 'Hortência Machele', gender: 'F', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-04-19', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st16', schoolId: 's1', classId: 'c1', frequencyNumber: 16, name: 'Inácio Tamele', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-09-08', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st17', schoolId: 's1', classId: 'c1', frequencyNumber: 17, name: 'Ismael Tembe', gender: 'M', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2006-05-23', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st18', schoolId: 's1', classId: 'c1', frequencyNumber: 18, name: 'Jacinto Munguambe', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-11-14', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st19', schoolId: 's1', classId: 'c1', frequencyNumber: 19, name: 'Jorge Mondlane', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-03-02', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st20', schoolId: 's1', classId: 'c1', frequencyNumber: 20, name: 'Kátia Bila', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2007-07-21', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // DIURNO / LABORAL: Turma B (Tarde) - 16 Alunos
    // -------------------------------------------------------------
    { id: 'st21', schoolId: 's1', classId: 'c2', frequencyNumber: 1, name: 'Leonardo Buque', gender: 'M', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2006-02-14', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st22', schoolId: 's1', classId: 'c2', frequencyNumber: 2, name: 'Manuel Chissano', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-03-19', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st23', schoolId: 's1', classId: 'c2', frequencyNumber: 3, name: 'Nilza Cuna', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2006-09-22', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st24', schoolId: 's1', classId: 'c2', frequencyNumber: 4, name: 'Osvaldo Zandamela', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-04-05', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st25', schoolId: 's1', classId: 'c2', frequencyNumber: 5, name: 'Paulo Guambe', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-11-17', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st26', schoolId: 's1', classId: 'c2', frequencyNumber: 6, name: 'Quintino Langa', gender: 'M', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2007-06-01', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st27', schoolId: 's1', classId: 'c2', frequencyNumber: 7, name: 'Rosa Manhiça', gender: 'F', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-08-15', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st28', schoolId: 's1', classId: 'c2', frequencyNumber: 8, name: 'Sérgio Vilanculos', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-01-29', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st29', schoolId: 's1', classId: 'c2', frequencyNumber: 9, name: 'Teresa Tivane', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2006-10-12', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st30', schoolId: 's1', classId: 'c2', frequencyNumber: 10, name: 'Tomás Langa', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2005-12-01', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st31', schoolId: 's1', classId: 'c2', frequencyNumber: 11, name: 'Ussene Saide', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2007-05-09', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st32', schoolId: 's1', classId: 'c2', frequencyNumber: 12, name: 'Valdemar Mucavele', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-04-26', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st33', schoolId: 's1', classId: 'c2', frequencyNumber: 13, name: 'Wilson Chiconela', gender: 'M', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2007-08-11', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st34', schoolId: 's1', classId: 'c2', frequencyNumber: 14, name: 'Xadreque Machava', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-07-03', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st35', schoolId: 's1', classId: 'c2', frequencyNumber: 15, name: 'Yolanda Macamo', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2007-02-18', enrollmentDate: '2024-01-12', status: 'active' as const },
    { id: 'st36', schoolId: 's1', classId: 'c2', frequencyNumber: 16, name: 'Zito Nhamposse', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2006-12-25', enrollmentDate: '2024-01-12', status: 'active' as const },

    // -------------------------------------------------------------
    // PÓS-LABORAL / NOTURNO: Turma C (Noite) - 10 Alunos
    // Ordem Alfabética Independente de A a Z
    // Contagem de Pauta continua de onde o Laboral terminou
    // -------------------------------------------------------------
    { id: 'st51', schoolId: 's1', classId: 'c3', frequencyNumber: 1, name: 'Abelardo Chirindza', gender: 'M', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2003-05-14', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st52', schoolId: 's1', classId: 'c3', frequencyNumber: 2, name: 'Belmira Muthemba', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2004-09-20', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st53', schoolId: 's1', classId: 'c3', frequencyNumber: 3, name: 'Cassiano Maluleque', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2002-11-08', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st54', schoolId: 's1', classId: 'c3', frequencyNumber: 4, name: 'Dionísio Muchanga', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2003-03-27', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st55', schoolId: 's1', classId: 'c3', frequencyNumber: 5, name: 'Elisa Maposse', gender: 'F', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2004-01-19', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st56', schoolId: 's1', classId: 'c3', frequencyNumber: 6, name: 'Fernando Nhatumbo', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2002-08-31', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st57', schoolId: 's1', classId: 'c3', frequencyNumber: 7, name: 'Gracinda Bila', gender: 'F', isNewAdmission: false, entryType: 'continuacao', birthDate: '2003-12-15', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st58', schoolId: 's1', classId: 'c3', frequencyNumber: 8, name: 'Hélder Macamo', gender: 'M', isNewAdmission: true, entryType: 'novo_ingresso', birthDate: '2004-06-04', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st59', schoolId: 's1', classId: 'c3', frequencyNumber: 9, name: 'Ilda Mondlane', gender: 'F', isNewAdmission: false, entryType: 'continuacao', birthDate: '2002-10-22', enrollmentDate: '2024-01-15', status: 'active' as const },
    { id: 'st60', schoolId: 's1', classId: 'c3', frequencyNumber: 10, name: 'Justino Sitoe', gender: 'M', isNewAdmission: false, entryType: 'continuacao', birthDate: '2003-07-11', enrollmentDate: '2024-01-15', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 1.ª CLASSE (Declaração 1º Ciclo Primário - Azul)
    // -------------------------------------------------------------
    { id: 'st_p1_1', schoolId: 's1', classId: 'c_p1', frequencyNumber: 1, name: 'Adilson Fernando Macamo', gender: 'M', fatherName: 'Fernando Macamo', motherName: 'Laura Nhantumbo', isNewAdmission: true, birthDate: '2018-05-14', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p1_2', schoolId: 's1', classId: 'c_p1', frequencyNumber: 2, name: 'Belmira Graça Cossa', gender: 'F', fatherName: 'Estêvão Cossa', motherName: 'Graça Mabunda', isNewAdmission: true, birthDate: '2018-09-22', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 2.ª CLASSE (Declaração 1º Ciclo Primário - Azul)
    // -------------------------------------------------------------
    { id: 'st_p2_1', schoolId: 's1', classId: 'c_p2', frequencyNumber: 1, name: 'Cláudio José Sitoe', gender: 'M', fatherName: 'José Sitoe', motherName: 'Ana Maria Cuna', isNewAdmission: false, birthDate: '2017-02-18', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p2_2', schoolId: 's1', classId: 'c_p2', frequencyNumber: 2, name: 'Dionísia Manuel Langa', gender: 'F', fatherName: 'Manuel Langa', motherName: 'Teresa Tivane', isNewAdmission: false, birthDate: '2017-07-30', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 3.ª CLASSE (Certificado 1º Ciclo Primário)
    // -------------------------------------------------------------
    { id: 'st_p3_1', schoolId: 's1', classId: 'c_p3', frequencyNumber: 1, name: 'Armando Manuel Mabunda', gender: 'M', fatherName: 'Manuel Mabunda', motherName: 'Graça Nhantumbo', isNewAdmission: true, birthDate: '2015-04-12', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p3_2', schoolId: 's1', classId: 'c_p3', frequencyNumber: 2, name: 'Carla Esperança Cossa', gender: 'F', fatherName: 'Estêvão Cossa', motherName: 'Júlia Manhiça', isNewAdmission: false, birthDate: '2015-09-20', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 4.ª CLASSE (Declaração 2º Ciclo Primário - Verde)
    // -------------------------------------------------------------
    { id: 'st_p4_1', schoolId: 's1', classId: 'c_p4', frequencyNumber: 1, name: 'Edilson Samuel Chiconela', gender: 'M', fatherName: 'Samuel Chiconela', motherName: 'Marta Buque', isNewAdmission: false, birthDate: '2014-03-12', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p4_2', schoolId: 's1', classId: 'c_p4', frequencyNumber: 2, name: 'Felisberta João Guambe', gender: 'F', fatherName: 'João Guambe', motherName: 'Rosália Mendes', isNewAdmission: false, birthDate: '2014-08-25', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 5.ª CLASSE (Declaração 2º Ciclo Primário - Verde)
    // -------------------------------------------------------------
    { id: 'st_p5_1', schoolId: 's1', classId: 'c_p5', frequencyNumber: 1, name: 'Gervásio Tomás Nhamposse', gender: 'M', fatherName: 'Tomás Nhamposse', motherName: 'Beatriz Cuamba', isNewAdmission: false, birthDate: '2013-06-19', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p5_2', schoolId: 's1', classId: 'c_p5', frequencyNumber: 2, name: 'Hermínia Paulo Vilanculos', gender: 'F', fatherName: 'Paulo Vilanculos', motherName: 'Elisa Maposse', isNewAdmission: false, birthDate: '2013-10-14', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 6.ª CLASSE (Certificado 2º Ciclo Primário)
    // -------------------------------------------------------------
    { id: 'st_p6_1', schoolId: 's1', classId: 'c_p6', frequencyNumber: 1, name: 'Dário Samuel Chichava', gender: 'M', fatherName: 'Samuel Chichava', motherName: 'Helena Macuácua', isNewAdmission: false, birthDate: '2012-07-15', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p6_2', schoolId: 's1', classId: 'c_p6', frequencyNumber: 2, name: 'Fabiola Teresa Mondlane', gender: 'F', fatherName: 'Tito Mondlane', motherName: 'Margarida Bila', isNewAdmission: false, birthDate: '2012-11-03', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 7.ª CLASSE (Declaração 3º Ciclo Básico - Bordô / Vinho)
    // -------------------------------------------------------------
    { id: 'st_p7_1', schoolId: 's1', classId: 'c_p7', frequencyNumber: 1, name: 'Isac Daniel Muchanga', gender: 'M', fatherName: 'Daniel Muchanga', motherName: 'Nilza Cuna', isNewAdmission: false, birthDate: '2011-01-20', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p7_2', schoolId: 's1', classId: 'c_p7', frequencyNumber: 2, name: 'Joana Carlos Matusse', gender: 'F', fatherName: 'Carlos Matusse', motherName: 'Filomena Zimba', isNewAdmission: false, birthDate: '2011-04-16', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 8.ª CLASSE (Declaração 3º Ciclo Básico - Bordô / Vinho)
    // -------------------------------------------------------------
    { id: 'st_p8_1', schoolId: 's1', classId: 'c_p8', frequencyNumber: 1, name: 'Kílian Vasco Tembe', gender: 'M', fatherName: 'Vasco Tembe', motherName: 'Hortência Machele', isNewAdmission: false, birthDate: '2010-09-08', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p8_2', schoolId: 's1', classId: 'c_p8', frequencyNumber: 2, name: 'Lurdes Bento Mondlane', gender: 'F', fatherName: 'Bento Mondlane', motherName: 'Kátia Bila', isNewAdmission: false, birthDate: '2010-12-05', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 9.ª CLASSE (Certificado Ensino Básico / 1º Ciclo ESG)
    // -------------------------------------------------------------
    { id: 'st_p9_1', schoolId: 's1', classId: 'c_p9', frequencyNumber: 1, name: 'Gerson Lucas Tamele', gender: 'M', fatherName: 'Lucas Tamele', motherName: 'Albertina Cuamba', isNewAdmission: false, birthDate: '2009-03-28', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p9_2', schoolId: 's1', classId: 'c_p9', frequencyNumber: 2, name: 'Ivone Marisa Zandamela', gender: 'F', fatherName: 'Alexandre Zandamela', motherName: 'Zita Langa', isNewAdmission: false, birthDate: '2009-08-19', enrollmentDate: '2024-01-10', status: 'active' as const },

    // -------------------------------------------------------------
    // ALUNOS 11.ª CLASSE (Declaração 2º Ciclo ESG - Índigo Real)
    // -------------------------------------------------------------
    { id: 'st_p11_1', schoolId: 's1', classId: 'c_p11', frequencyNumber: 1, name: 'Mauro António Nhaca', gender: 'M', fatherName: 'António Nhaca', motherName: 'Fátima Nhaca', isNewAdmission: false, birthDate: '2006-05-11', enrollmentDate: '2024-01-10', status: 'active' as const },
    { id: 'st_p11_2', schoolId: 's1', classId: 'c_p11', frequencyNumber: 2, name: 'Nércia Sebastião Cuco', gender: 'F', fatherName: 'Sebastião Cuco', motherName: 'Ercília Nhantumbo', isNewAdmission: false, birthDate: '2006-10-09', enrollmentDate: '2024-01-10', status: 'active' as const },
  ],
  subjects: [
    { id: 'sub4', name: 'Português', area: 'CS' },
    { id: 'sub5', name: 'Inglês', area: 'CS' },
    { id: 'sub6', name: 'Francês', area: 'CS' },
    { id: 'sub7', name: 'História', area: 'CS' },
    { id: 'sub8', name: 'Geografia', area: 'CS' },
    { id: 'sub1', name: 'Matemática', area: 'MCN' },
    { id: 'sub9', name: 'Biologia', area: 'MCN' },
    { id: 'sub3', name: 'Química', area: 'MCN' },
    { id: 'sub2', name: 'Física', area: 'MCN' },
    { id: 'sub10', name: 'Ed. Visual', area: 'APTP' },
    { id: 'sub11', name: 'Ed. Física', area: 'APTP' },
    { id: 'sub12', name: 'TICs', area: 'APTP' },
    { id: 'sub13', name: 'N. Empre', area: 'APTP' },
    { id: 'sub14', name: 'Agro. Pec.', area: 'APTP' },
  ],
  assignments: [
    { id: 'a1', teacherId: 'u4', classId: 'c1', subjectId: 'sub1' },
    { id: 'a2', teacherId: 'u4', classId: 'c1', subjectId: 'sub2' },
    { id: 'a3', teacherId: 'u4', classId: 'c1', subjectId: 'sub3' },
    { id: 'a4', teacherId: 'u4', classId: 'c1', subjectId: 'sub4' },
    { id: 'a5', teacherId: 'u4', classId: 'c2', subjectId: 'sub1' },
  ],
  grades: (() => {
    const list: Grade[] = [];
    const subs = [
      'sub4', 'sub5', 'sub6', 'sub7', 'sub8', 
      'sub1', 'sub9', 'sub3', 'sub2', 
      'sub10', 'sub11', 'sub12', 'sub13', 'sub14'
    ];

    // Student IDs and their base average
    // Dispensados: st01 (Afonso), st04 (Carlos), st14 (Helena) -> MF >= 14
    // Excluídos: st10 (Fátima), st30 (Tomás Langa) -> MF < 9
    // All others: Admitidos -> MF between 10 and 12
    const studentIds = [
      // Turma A (c1)
      'st01', 'st02', 'st03', 'st04', 'st05', 'st06', 'st07', 'st08', 'st09', 'st10',
      'st11', 'st12', 'st13', 'st14', 'st15', 'st16', 'st17', 'st18', 'st19', 'st20',
      // Turma B (c2)
      'st21', 'st22', 'st23', 'st24', 'st25', 'st26', 'st27', 'st28', 'st29', 'st30',
      'st31', 'st32', 'st33', 'st34', 'st35', 'st36',
      // Turma C (c3 - Pós-Laboral)
      'st51', 'st52', 'st53', 'st54', 'st55', 'st56', 'st57', 'st58', 'st59', 'st60'
    ];

    studentIds.forEach(sId => {
      let baseVal = 11;
      let classId = 'c1';
      if (['st21','st22','st23','st24','st25','st26','st27','st28','st29','st30','st31','st32','st33','st34','st35','st36'].includes(sId)) {
        classId = 'c2';
      } else if (['st51','st52','st53','st54','st55','st56','st57','st58','st59','st60'].includes(sId)) {
        classId = 'c3';
      }

      if (['st01', 'st04', 'st14'].includes(sId)) {
        baseVal = 15; // Dispensado
      } else if (['st10', 'st30'].includes(sId)) {
        baseVal = 7; // Excluído
      } else {
        baseVal = 10 + (parseInt(sId.replace('st', ''), 10) % 3); // 10, 11, or 12 -> Admitido
      }

      subs.forEach((subId, subIdx) => {
        const offset = (subIdx % 3) - 1;
        const val = Math.max(5, Math.min(19, baseVal + offset));
        
        // Trimester 1
        list.push({
          id: `g-${sId}-${subId}-t1`,
          studentId: sId,
          classId,
          subjectId: subId,
          teacherId: 'u4',
          trimester: 1,
          acs1: val,
          acs2: val,
          acs3: val,
          apt: val,
          media: val,
          isLocked: true
        });

        // Trimester 2
        list.push({
          id: `g-${sId}-${subId}-t2`,
          studentId: sId,
          classId,
          subjectId: subId,
          teacherId: 'u4',
          trimester: 2,
          acs1: val,
          acs2: val,
          acs3: val,
          apt: val,
          media: val,
          isLocked: true
        });

        // Trimester 3
        list.push({
          id: `g-${sId}-${subId}-t3`,
          studentId: sId,
          classId,
          subjectId: subId,
          teacherId: 'u4',
          trimester: 3,
          acs1: val,
          acs2: val,
          acs3: val,
          apt: val,
          media: val,
          isLocked: true
        });
      });
    });

    return list;
  })(),
  examGrades: [] as ExamGrade[],
  reports: [] as TrimesterReport[],
  employees: [
    {
      id: 'CAL-102938475',
      schoolId: 's1',
      name: 'Carlos Alberto Langa',
      gender: 'M',
      nuit: '102938475',
      email: 'carlos.langa@mined.gov.mz',
      phone: '+258 84 391 8294',
      maritalStatus: 'Casado',
      fatherName: 'Alberto Langa',
      motherName: 'Maria Chissano Langa',
      idCardNumber: '110100482910M',
      idCardIssuedAt: 'Matola',
      idCardIssuedDate: '2018-04-12',
      nationality: 'Moçambicana',
      birthProvince: 'Maputo Província',
      birthDistrict: 'Matola (Cidade)',
      birthDate: '1982-05-14',
      address: 'Bairro da Liberdade, Rua 12, Casa 45',
      neighborhood: 'Liberdade',
      residenceDistrict: 'Matola (Cidade)',
      cell: 'B',
      blockNo: '14',
      houseNo: '45',
      childrenCount: 3,
      career: 'Docente',
      category: 'Docente N1',
      roleFunction: 'Professor de Matemática e Delegado de Disciplina',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2010-02-01',
      academicLevel: 'Licenciatura',
      trainingArea: 'Ensino de Matemática',
      leadershipRole: 'Delegado de Disciplina',
      taughtSubjects: ['Matemática']
    },
    {
      id: 'ABM-201948392',
      schoolId: 's1',
      name: 'Ana Beatriz Machava',
      gender: 'F',
      nuit: '201948392',
      email: 'ana.machava@mined.gov.mz',
      phone: '+258 82 918 2741',
      maritalStatus: 'Solteiro',
      fatherName: 'Beatriz Machava Pai',
      motherName: 'Rosa Tembe Machava',
      idCardNumber: '110200847291F',
      idCardIssuedAt: 'Chókwè',
      idCardIssuedDate: '2019-09-20',
      nationality: 'Moçambicana',
      birthProvince: 'Gaza',
      birthDistrict: 'Chókwè',
      birthDate: '1979-11-20',
      address: 'Av. Eduardo Mondlane, Q. 8',
      neighborhood: 'Central',
      residenceDistrict: 'Maputo Cidade',
      cell: 'A',
      blockNo: '08',
      houseNo: '12',
      childrenCount: 2,
      career: 'CTA',
      category: 'Técnico Superior N1',
      roleFunction: 'Chefe da Secretaria Geral',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2008-06-15',
      academicLevel: 'Licenciatura',
      trainingArea: 'Administração Pública e Gestão de RH',
      leadershipRole: 'Chefe de Secretaria',
      taughtSubjects: []
    },
    {
      id: 'TEC-309482716',
      schoolId: 's1',
      name: 'Tomás Estêvão Cossa',
      gender: 'M',
      nuit: '309482716',
      email: 'tomas.cossa@mined.gov.mz',
      phone: '+258 87 501 9283',
      maritalStatus: 'Casado',
      fatherName: 'Estêvão Cossa',
      motherName: 'Margarida Sitoe Cossa',
      idCardNumber: '110300192847T',
      idCardIssuedAt: 'Beira',
      idCardIssuedDate: '2017-03-10',
      nationality: 'Moçambicana',
      birthProvince: 'Sofala',
      birthDistrict: 'Beira (Cidade)',
      birthDate: '1985-08-09',
      address: 'Bairro Ponta Gêa, Rua 4',
      neighborhood: 'Ponta Gêa',
      residenceDistrict: 'Beira (Cidade)',
      cell: 'C',
      blockNo: '22',
      houseNo: '10',
      childrenCount: 2,
      career: 'Docente',
      category: 'Docente N1',
      roleFunction: 'Director Adjunto Pedagógico',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2012-01-15',
      academicLevel: 'Mestrado',
      trainingArea: 'Gestão Educacional e Física',
      leadershipRole: 'Director Adjunto Pedagógico',
      taughtSubjects: ['Física']
    },
    {
      id: 'MHM-401928374',
      schoolId: 's1',
      name: 'Maria Helena Mabunda',
      gender: 'F',
      nuit: '401928374',
      email: 'maria.mabunda@mined.gov.mz',
      phone: '+258 84 990 1284',
      maritalStatus: 'Casado',
      fatherName: 'Helena Mabunda',
      motherName: 'Joana Guambe',
      idCardNumber: '110400582910H',
      idCardIssuedAt: 'Maxixe',
      idCardIssuedDate: '2020-01-18',
      nationality: 'Moçambicana',
      birthProvince: 'Inhambane',
      birthDistrict: 'Maxixe (Cidade)',
      birthDate: '1990-03-27',
      address: 'Bairro Chambone, Rua 3',
      neighborhood: 'Chambone',
      residenceDistrict: 'Maxixe (Cidade)',
      cell: 'A',
      blockNo: '05',
      houseNo: '18',
      childrenCount: 1,
      career: 'Docente',
      category: 'Docente N2',
      roleFunction: 'Professora de Língua Portuguesa',
      isEffective: 'Não',
      contractType: 'Contrato a Termo Certo',
      contractLink: 'Contratado do Estado',
      admissionDate: '2021-02-01',
      academicLevel: 'Licenciatura',
      trainingArea: 'Ensino de Língua Portuguesa',
      leadershipRole: 'Directora de Turma',
      taughtSubjects: ['Português']
    },
    // Mais Docentes
    {
      id: 'ASM-501928471',
      schoolId: 's1',
      name: 'Arlindo Sérgio Macuácua',
      gender: 'M',
      nuit: '501928471',
      email: 'arlindo.macuacua@mined.gov.mz',
      phone: '+258 84 210 3948',
      maritalStatus: 'Casado',
      fatherName: 'Sérgio Macuácua',
      motherName: 'Emília Chissano',
      idCardNumber: '110500392810K',
      idCardIssuedAt: 'Xai-Xai',
      idCardIssuedDate: '2016-05-14',
      nationality: 'Moçambicana',
      birthProvince: 'Gaza',
      birthDistrict: 'Xai-Xai',
      birthDate: '1984-11-19',
      address: 'Bairro 2, Casa 15',
      neighborhood: 'Marien Ngouabi',
      residenceDistrict: 'Xai-Xai',
      cell: 'B',
      blockNo: '04',
      houseNo: '15',
      childrenCount: 2,
      career: 'Docente',
      category: 'Docente N1',
      roleFunction: 'Professor de Química',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2011-03-01',
      academicLevel: 'Licenciatura',
      trainingArea: 'Ensino de Química e Biologia',
      leadershipRole: 'Delegado de Disciplina',
      taughtSubjects: ['Química']
    },
    {
      id: 'JAS-601928582',
      schoolId: 's1',
      name: 'Joana Amélia Sitoe',
      gender: 'F',
      nuit: '601928582',
      email: 'joana.sitoe@mined.gov.mz',
      phone: '+258 82 490 1827',
      maritalStatus: 'Casado',
      fatherName: 'Américo Sitoe',
      motherName: 'Teresa Langa Sitoe',
      idCardNumber: '110600492811L',
      idCardIssuedAt: 'Maputo',
      idCardIssuedDate: '2015-11-20',
      nationality: 'Moçambicana',
      birthProvince: 'Maputo Cidade',
      birthDistrict: 'KaMpfumo',
      birthDate: '1983-04-12',
      address: 'Bairro da Malhangalene, Rua 5',
      neighborhood: 'Malhangalene',
      residenceDistrict: 'Maputo Cidade',
      cell: 'A',
      blockNo: '12',
      houseNo: '44',
      childrenCount: 3,
      career: 'Docente',
      category: 'Docente N1',
      roleFunction: 'Professora de Biologia',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2009-08-01',
      academicLevel: 'Mestrado',
      trainingArea: 'Ciências Biológicas e Didáctica',
      leadershipRole: 'Directora de Turma',
      taughtSubjects: ['Biologia']
    },
    {
      id: 'FZT-701928693',
      schoolId: 's1',
      name: 'Feliciano Zacarias Tembe',
      gender: 'M',
      nuit: '701928693',
      email: 'feliciano.tembe@mined.gov.mz',
      phone: '+258 87 392 0192',
      maritalStatus: 'Solteiro',
      fatherName: 'Zacarias Tembe',
      motherName: 'Júlia Vilanculos',
      idCardNumber: '110700592812M',
      idCardIssuedAt: 'Inhambane',
      idCardIssuedDate: '2019-02-15',
      nationality: 'Moçambicana',
      birthProvince: 'Inhambane',
      birthDistrict: 'Homoíne',
      birthDate: '1988-09-05',
      address: 'Bairro Liberdade, Rua 8',
      neighborhood: 'Liberdade',
      residenceDistrict: 'Matola',
      cell: 'D',
      blockNo: '18',
      houseNo: '23',
      childrenCount: 0,
      career: 'Docente',
      category: 'Docente N2',
      roleFunction: 'Professor de História',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2018-02-01',
      academicLevel: 'Licenciatura',
      trainingArea: 'Ensino de História de Moçambique e Geral',
      leadershipRole: 'Delegado de Disciplina',
      taughtSubjects: ['História']
    },
    {
      id: 'LEM-801928704',
      schoolId: 's1',
      name: 'Lurdes Ernesto Mondlane',
      gender: 'F',
      nuit: '801928704',
      email: 'lurdes.mondlane@mined.gov.mz',
      phone: '+258 84 582 9102',
      maritalStatus: 'Casado',
      fatherName: 'Ernesto Mondlane',
      motherName: 'Graça Nhaca',
      idCardNumber: '110800692813N',
      idCardIssuedAt: 'Chibuto',
      idCardIssuedDate: '2017-08-22',
      nationality: 'Moçambicana',
      birthProvince: 'Gaza',
      birthDistrict: 'Chibuto',
      birthDate: '1987-12-03',
      address: 'Bairro Central, Av. 24 de Julho',
      neighborhood: 'Central',
      residenceDistrict: 'Maputo Cidade',
      cell: 'B',
      blockNo: '06',
      houseNo: '19',
      childrenCount: 2,
      career: 'Docente',
      category: 'Docente N1',
      roleFunction: 'Professora de Geografia',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2014-04-15',
      academicLevel: 'Licenciatura',
      trainingArea: 'Geografia e Planeamento Físico',
      leadershipRole: 'Directora de Turma',
      taughtSubjects: ['Geografia']
    },
    {
      id: 'SPC-901928815',
      schoolId: 's1',
      name: 'Samuel Paulo Chissano',
      gender: 'M',
      nuit: '901928815',
      email: 'samuel.chissano@mined.gov.mz',
      phone: '+258 86 492 8172',
      maritalStatus: 'Solteiro',
      fatherName: 'Paulo Chissano',
      motherName: 'Marta Buque',
      idCardNumber: '110900792814P',
      idCardIssuedAt: 'Nampula',
      idCardIssuedDate: '2021-04-10',
      nationality: 'Moçambicana',
      birthProvince: 'Nampula',
      birthDistrict: 'Nampula (Cidade)',
      birthDate: '1992-06-18',
      address: 'Bairro Muatala, Rua Principal',
      neighborhood: 'Muatala',
      residenceDistrict: 'Nampula (Cidade)',
      cell: 'C',
      blockNo: '11',
      houseNo: '07',
      childrenCount: 1,
      career: 'Docente',
      category: 'Docente N2',
      roleFunction: 'Professor de Língua Inglesa',
      isEffective: 'Não',
      contractType: 'Contrato a Termo Certo',
      contractLink: 'Contratado do Estado',
      admissionDate: '2022-02-01',
      academicLevel: 'Licenciatura',
      trainingArea: 'Ensino de Língua Inglesa',
      leadershipRole: 'Docente',
      taughtSubjects: ['Inglês']
    },
    {
      id: 'BXN-101928926',
      schoolId: 's1',
      name: 'Bento Xavier Nhamposse',
      gender: 'M',
      nuit: '101928926',
      email: 'bento.nhamposse@mined.gov.mz',
      phone: '+258 82 710 4928',
      maritalStatus: 'Casado',
      fatherName: 'Xavier Nhamposse',
      motherName: 'Flora Bila',
      idCardNumber: '111000892815Q',
      idCardIssuedAt: 'Maputo',
      idCardIssuedDate: '2014-07-30',
      nationality: 'Moçambicana',
      birthProvince: 'Maputo Província',
      birthDistrict: 'Boane',
      birthDate: '1981-01-25',
      address: 'Vila de Boane, Rua 3',
      neighborhood: 'Boane Sede',
      residenceDistrict: 'Boane',
      cell: 'A',
      blockNo: '02',
      houseNo: '55',
      childrenCount: 4,
      career: 'Docente',
      category: 'Docente N3',
      roleFunction: 'Professor de Educação Física',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2006-03-01',
      academicLevel: 'Médio',
      trainingArea: 'Educação Física e Desporto Escolar',
      leadershipRole: 'Responsável do Desporto Escolar',
      taughtSubjects: ['Ed. Física']
    },
    // Mais CTA (Corpo Técnico-Administrativo)
    {
      id: 'ESG-201928037',
      schoolId: 's1',
      name: 'Ernesto Salvador Guambe',
      gender: 'M',
      nuit: '201928037',
      email: 'ernesto.guambe@mined.gov.mz',
      phone: '+258 84 928 3741',
      maritalStatus: 'Casado',
      fatherName: 'Salvador Guambe',
      motherName: 'Anita Cossa',
      idCardNumber: '111100992816R',
      idCardIssuedAt: 'Maputo',
      idCardIssuedDate: '2016-10-18',
      nationality: 'Moçambicana',
      birthProvince: 'Maputo Província',
      birthDistrict: 'Manhiça',
      birthDate: '1980-03-14',
      address: 'Bairro Fomento, Rua das Flores',
      neighborhood: 'Fomento',
      residenceDistrict: 'Matola',
      cell: 'B',
      blockNo: '09',
      houseNo: '31',
      childrenCount: 3,
      career: 'CTA',
      category: 'Técnico Superior N1',
      roleFunction: 'Responsável de Finanças e Tesouraria',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2010-09-01',
      academicLevel: 'Licenciatura',
      trainingArea: 'Contabilidade e Auditoria Pública',
      leadershipRole: 'Tesoureiro',
      taughtSubjects: []
    },
    {
      id: 'MPM-301928148',
      schoolId: 's1',
      name: 'Marta Paulino Matsinhe',
      gender: 'F',
      nuit: '301928148',
      email: 'marta.matsinhe@mined.gov.mz',
      phone: '+258 82 301 9284',
      maritalStatus: 'Solteiro',
      fatherName: 'Paulino Matsinhe',
      motherName: 'Leonor Cuamba',
      idCardNumber: '111200092817S',
      idCardIssuedAt: 'Chókwè',
      idCardIssuedDate: '2018-06-12',
      nationality: 'Moçambicana',
      birthProvince: 'Gaza',
      birthDistrict: 'Guijá',
      birthDate: '1986-10-29',
      address: 'Bairro Machava-Socimol, Rua 7',
      neighborhood: 'Machava',
      residenceDistrict: 'Matola',
      cell: 'A',
      blockNo: '14',
      houseNo: '28',
      childrenCount: 1,
      career: 'CTA',
      category: 'Técnico Profissional',
      roleFunction: 'Oficial de Matrículas e Processos Individuais',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2013-05-15',
      academicLevel: 'Médio',
      trainingArea: 'Administração e Gestão de Documentos',
      leadershipRole: 'Secretaria',
      taughtSubjects: []
    },
    {
      id: 'ASC-401928259',
      schoolId: 's1',
      name: 'Alberto Salomão Cuamba',
      gender: 'M',
      nuit: '401928259',
      email: 'alberto.cuamba@mined.gov.mz',
      phone: '+258 87 192 8374',
      maritalStatus: 'Casado',
      fatherName: 'Salomão Cuamba',
      motherName: 'Elisa Zandamela',
      idCardNumber: '111300192818T',
      idCardIssuedAt: 'Quelimane',
      idCardIssuedDate: '2015-09-04',
      nationality: 'Moçambicana',
      birthProvince: 'Zambézia',
      birthDistrict: 'Quelimane',
      birthDate: '1978-07-22',
      address: 'Bairro Central, Av. Maguiguana',
      neighborhood: 'Central',
      residenceDistrict: 'Maputo Cidade',
      cell: 'C',
      blockNo: '03',
      houseNo: '10',
      childrenCount: 2,
      career: 'CTA',
      category: 'Técnico Superior N2',
      roleFunction: 'Bibliotecário Chefe e Gestor do Centro de Recursos',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2011-01-20',
      academicLevel: 'Licenciatura',
      trainingArea: 'Ciências de Informação e Biblioteconomia',
      leadershipRole: 'Bibliotecário Chefe',
      taughtSubjects: []
    },
    {
      id: 'JVZ-501928360',
      schoolId: 's1',
      name: 'Jaime Valente Zandamela',
      gender: 'M',
      nuit: '501928360',
      email: 'jaime.zandamela@mined.gov.mz',
      phone: '+258 84 719 2831',
      maritalStatus: 'Solteiro',
      fatherName: 'Valente Zandamela',
      motherName: 'Constância Sitoe',
      idCardNumber: '111400292819U',
      idCardIssuedAt: 'Matola',
      idCardIssuedDate: '2022-03-15',
      nationality: 'Moçambicana',
      birthProvince: 'Maputo Província',
      birthDistrict: 'Matola',
      birthDate: '1995-12-08',
      address: 'Bairro Trevo, Rua 2',
      neighborhood: 'Trevo',
      residenceDistrict: 'Matola',
      cell: 'D',
      blockNo: '08',
      houseNo: '14',
      childrenCount: 0,
      career: 'CTA',
      category: 'Técnico de Informática',
      roleFunction: 'Administrador de Rede e Suporte Tecnológico',
      isEffective: 'Não',
      contractType: 'Contrato a Termo Certo',
      contractLink: 'Contratado do Estado',
      admissionDate: '2023-01-10',
      academicLevel: 'Médio',
      trainingArea: 'Técnico de Informática e Redes de Computadores',
      leadershipRole: 'Suporte TIC',
      taughtSubjects: []
    },
    {
      id: 'PFL-601928471',
      schoolId: 's1',
      name: 'Pedro Fernando Langa',
      gender: 'M',
      nuit: '601928471',
      email: 'pedro.langa@mined.gov.mz',
      phone: '+258 82 829 1047',
      maritalStatus: 'Casado',
      fatherName: 'Fernando Langa',
      motherName: 'Belmira Cossa',
      idCardNumber: '111500392820V',
      idCardIssuedAt: 'Chókwè',
      idCardIssuedDate: '2012-08-19',
      nationality: 'Moçambicana',
      birthProvince: 'Gaza',
      birthDistrict: 'Chókwè',
      birthDate: '1975-04-16',
      address: 'Bairro T3, Rua 11',
      neighborhood: 'T3',
      residenceDistrict: 'Matola',
      cell: 'B',
      blockNo: '21',
      houseNo: '88',
      childrenCount: 5,
      career: 'CTA',
      category: 'Agente de Serviço e Segurança',
      roleFunction: 'Encarregado de Portaria e Segurança Patrimonial',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2005-02-15',
      academicLevel: 'Básico',
      trainingArea: 'Segurança e Vigilância Física',
      leadershipRole: 'Chefe de Segurança',
      taughtSubjects: []
    },
    {
      id: 'RDN-701928582',
      schoolId: 's1',
      name: 'Rosa Dulce Nhantumbo',
      gender: 'F',
      nuit: '701928582',
      email: 'rosa.nhantumbo@mined.gov.mz',
      phone: '+258 86 501 9283',
      maritalStatus: 'Viúvo',
      fatherName: 'Dulce Nhantumbo',
      motherName: 'Albertina Tembe',
      idCardNumber: '111600492821W',
      idCardIssuedAt: 'Maputo',
      idCardIssuedDate: '2013-04-25',
      nationality: 'Moçambicana',
      birthProvince: 'Maputo Província',
      birthDistrict: 'Marracuene',
      birthDate: '1977-08-30',
      address: 'Bairro Zimpeto, Rua das Acácias',
      neighborhood: 'Zimpeto',
      residenceDistrict: 'Maputo Cidade',
      cell: 'A',
      blockNo: '05',
      houseNo: '16',
      childrenCount: 3,
      career: 'CTA',
      category: 'Auxiliar Administrativo',
      roleFunction: 'Encarregada de Higiene e Manutenção das Instalações',
      isEffective: 'Sim',
      contractType: 'Nomeação Definitiva',
      contractLink: 'Quadro de Nomeação',
      admissionDate: '2007-07-01',
      academicLevel: 'Básico',
      trainingArea: 'Higiene e Sanitação Escolar',
      leadershipRole: 'Encarregada de Limpeza',
      taughtSubjects: []
    }
  ] as Employee[],
  collectionPeriods: [
    {
      id: 'period-1',
      title: 'Recolha Estatística Trimestral - Q1 2026',
      description: 'Recolha obrigatória de dados de aproveitamento e efetivo escolar.',
      startDate: '2026-03-20',
      endDate: '2026-03-31',
      status: 'published',
      createdByRole: 'national',
      targetLevel: 'school',
      createdAt: '2026-03-01T10:00:00Z'
    }
  ],
  collectionForms: [],
  transferRequests: [],
  academicComplaints: [],
  chatMessages: [
    {
      id: 'msg-1',
      senderId: 'u6',
      senderName: 'Ministro da Educação',
      senderRole: 'national',
      receiverLevel: 'provincial',
      text: 'Bem-vindos ao novo sistema de coordenação nacional EduGestão.',
      timestamp: '2026-03-01T11:00:00Z'
    }
  ],
  financialTransactions: [
    {
      id: 'ft-001',
      schoolId: 's1',
      type: 'receita' as const,
      category: 'Propinas' as const,
      amount: 45000,
      date: '2026-03-15',
      description: 'Pagamento de Propinas Trimestrais - 10ª Classe Turma A (15 alunos)',
      referenceNumber: 'REC-2026-03-089',
      payerBeneficiary: 'Encarregados de Educação - Turma A',
      paymentMethod: 'M-Pesa' as const,
      status: 'pago' as const,
      month: 'Março',
      year: 2026
    },
    {
      id: 'ft-002',
      schoolId: 's1',
      type: 'receita' as const,
      category: 'Taxas' as const,
      amount: 18500,
      date: '2026-03-18',
      description: 'Emissão de Certificados e Declarações com Notas Oficiais',
      referenceNumber: 'REC-2026-03-112',
      payerBeneficiary: 'Diversos Utentes da Secretaria',
      paymentMethod: 'POS' as const,
      status: 'pago' as const,
      month: 'Março',
      year: 2026
    },
    {
      id: 'ft-003',
      schoolId: 's1',
      type: 'despesa' as const,
      category: 'Energia' as const,
      amount: 14200,
      date: '2026-03-10',
      description: 'Factura Mensal EDM - Electricidade de Moçambique (Bloco Principal e Salas)',
      referenceNumber: 'DSP-EDM-2026-03',
      payerBeneficiary: 'EDM - Electricidade de Moçambique',
      paymentMethod: 'Transferência Bancária' as const,
      status: 'pago' as const,
      month: 'Março',
      year: 2026
    },
    {
      id: 'ft-004',
      schoolId: 's1',
      type: 'despesa' as const,
      category: 'Água' as const,
      amount: 8750,
      date: '2026-03-12',
      description: 'Factura FIPAG - Abastecimento de Água e Sanitação Escolar',
      referenceNumber: 'DSP-FIPAG-2026-03',
      payerBeneficiary: 'FIPAG Maputo',
      paymentMethod: 'Transferência Bancária' as const,
      status: 'pago' as const,
      month: 'Março',
      year: 2026
    },
    {
      id: 'ft-005',
      schoolId: 's1',
      type: 'despesa' as const,
      category: 'Material Escolar' as const,
      amount: 22000,
      date: '2026-03-14',
      description: 'Aquisição de Resmas de Papel A4, Giz Antialérgico e Marcadores',
      referenceNumber: 'DSP-MAT-2026-041',
      payerBeneficiary: 'Papelaria Académica Lda',
      paymentMethod: 'Transferência Bancária' as const,
      status: 'pago' as const,
      month: 'Março',
      year: 2026
    },
    {
      id: 'ft-006',
      schoolId: 's1',
      type: 'despesa' as const,
      category: 'Salários' as const,
      amount: 380000,
      date: '2026-02-28',
      description: 'Folha de Pagamento - Pessoal Docente e CTA do Regime Contratado',
      referenceNumber: 'SAL-2026-02-FOLHA',
      payerBeneficiary: 'Quadro Contratado da Escola',
      paymentMethod: 'Transferência Bancária' as const,
      status: 'pago' as const,
      month: 'Fevereiro',
      year: 2026
    }
  ],
  patrimonyItems: [
    {
      id: 'pat-001',
      schoolId: 's1',
      code: 'PAT-INF-001',
      name: 'Computador Desktop HP ProDesk Core i5',
      category: 'Computadores' as const,
      status: 'Bom' as const,
      locationRoom: 'Laboratório de Informática 1',
      acquisitionDate: '2023-04-10',
      acquisitionValue: 38500,
      serialNumber: 'HP-SN-994821',
      responsiblePerson: 'Eng. Alberto Sithole',
      notes: 'Equipamento em pleno funcionamento com Linux e suíte de escritório.'
    },
    {
      id: 'pat-002',
      schoolId: 's1',
      code: 'PAT-INF-002',
      name: 'Projetor Multimédia Epson 3LCD 3600 Lumens',
      category: 'Equipamentos' as const,
      status: 'Bom' as const,
      locationRoom: 'Sala de Conferências / Sala 4',
      acquisitionDate: '2024-02-15',
      acquisitionValue: 42000,
      serialNumber: 'EPSON-X41-8842',
      responsiblePerson: 'Eng. Alberto Sithole',
      notes: 'Utilizado para aulas magnas e reuniões pedagógicas.'
    },
    {
      id: 'pat-003',
      schoolId: 's1',
      code: 'PAT-MOB-010',
      name: 'Conjunto de 50 Carteiras Escolares Duplas em Madeira e Metal',
      category: 'Mobiliário' as const,
      status: 'Bom' as const,
      locationRoom: 'Bloco B - Salas 7 e 8',
      acquisitionDate: '2022-08-20',
      acquisitionValue: 125000,
      responsiblePerson: 'Eng. Alberto Sithole',
      notes: 'Mobiliário padrão MINEDH reforçado.'
    },
    {
      id: 'pat-004',
      schoolId: 's1',
      code: 'PAT-LAB-005',
      name: 'Microscópio Óptico Binocular 1600x',
      category: 'Laboratórios' as const,
      status: 'Bom' as const,
      locationRoom: 'Laboratório de Biologia e Química',
      acquisitionDate: '2023-09-05',
      acquisitionValue: 28000,
      serialNumber: 'OPT-MIC-2023-44',
      responsiblePerson: 'Profa. Sofia Langa',
      notes: 'Equipamento de experimentação prática laboratorial.'
    },
    {
      id: 'pat-005',
      schoolId: 's1',
      code: 'PAT-AUT-001',
      name: 'Minibus Toyota HiAce 15 Lugares (Transporte de Apoio Escolar)',
      category: 'Viaturas' as const,
      status: 'Regular' as const,
      locationRoom: 'Garagem / Parque Automóvel',
      acquisitionDate: '2020-11-12',
      acquisitionValue: 850000,
      serialNumber: 'MMT-88-42-MC',
      responsiblePerson: 'Sr. Ernesto Macamo',
      notes: 'Viatura de apoio a visitas de estudo e serviços administrativos.'
    }
  ],
  patrimonyMovements: [
    {
      id: 'mov-001',
      schoolId: 's1',
      itemId: 'pat-001',
      itemName: 'Computador Desktop HP ProDesk Core i5',
      type: 'Aquisição' as const,
      date: '2023-04-10',
      toLocation: 'Laboratório de Informática 1',
      reason: 'Equipamento adquirido pelo Fundo de Apoio ao Sector de Educação',
      registeredBy: 'Eng. Alberto Sithole'
    },
    {
      id: 'mov-002',
      schoolId: 's1',
      itemId: 'pat-002',
      itemName: 'Projetor Multimédia Epson',
      type: 'Movimentação' as const,
      date: '2026-02-10',
      fromLocation: 'Gabinete Pedagógico',
      toLocation: 'Sala de Conferências',
      reason: 'Reinstalação permanente para suporte a apresentações',
      registeredBy: 'Eng. Alberto Sithole'
    }
  ],
  libraryBooks: [
    {
      id: 'bk-001',
      schoolId: 's1',
      title: 'Terra Sonâmbula',
      author: 'Mia Couto',
      isbn: '978-972-21-0731-9',
      category: 'Literatura Moçambicana',
      gradeLevel: '10.ª à 12.ª Classe',
      totalCopies: 45,
      availableCopies: 38,
      shelfLocation: 'Estante A3 - Lit. Nacional',
      yearPublished: 1992,
      publisher: 'Editora Ndjira'
    },
    {
      id: 'bk-002',
      schoolId: 's1',
      title: 'Matemática 10.ª Classe - Livro do Aluno',
      author: 'MINEDH / Diname',
      isbn: '978-989-50-1204-1',
      category: 'Manual Escolar',
      gradeLevel: '10.ª Classe',
      totalCopies: 120,
      availableCopies: 95,
      shelfLocation: 'Estante M1 - Manuais Oficiais',
      yearPublished: 2024,
      publisher: 'Diname'
    },
    {
      id: 'bk-003',
      schoolId: 's1',
      title: 'Ualalapi',
      author: 'Ungulani Ba Ka Khosa',
      isbn: '978-972-21-0428-8',
      category: 'Literatura Moçambicana / Histórica',
      gradeLevel: '11.ª e 12.ª Classe',
      totalCopies: 30,
      availableCopies: 24,
      shelfLocation: 'Estante A3 - Lit. Nacional',
      yearPublished: 1987,
      publisher: 'Associação dos Escritores Moçambicanos'
    },
    {
      id: 'bk-004',
      schoolId: 's1',
      title: 'Física 10.ª Classe - Teoria e Prática',
      author: 'Manuel Mabote & Carlos Langa',
      isbn: '978-989-52-4411-0',
      category: 'Ciências Naturais',
      gradeLevel: '10.ª Classe',
      totalCopies: 80,
      availableCopies: 62,
      shelfLocation: 'Estante F2 - Ciências Exactas',
      yearPublished: 2023,
      publisher: 'Texto Editores'
    },
    {
      id: 'bk-005',
      schoolId: 's1',
      title: 'Dicionário da Língua Portuguesa Contemporânea',
      author: 'Academia das Ciências',
      isbn: '978-972-24-1188-1',
      category: 'Obras de Referência',
      gradeLevel: 'Geral',
      totalCopies: 15,
      availableCopies: 12,
      shelfLocation: 'Mesa de Consulta / Dicionários',
      yearPublished: 2021,
      publisher: 'Verbo'
    }
  ],
  libraryLoans: [
    {
      id: 'ln-001',
      schoolId: 's1',
      bookId: 'bk-001',
      bookTitle: 'Terra Sonâmbula',
      userType: 'aluno' as const,
      userId: 'st01',
      userName: 'Afonso Matsinhe',
      loanDate: '2026-03-10',
      expectedReturnDate: '2026-03-24',
      status: 'Activo' as const,
      notes: 'Livro emprestado para análise literária na disciplina de Português.'
    },
    {
      id: 'ln-002',
      schoolId: 's1',
      bookId: 'bk-003',
      bookTitle: 'Ualalapi',
      userType: 'aluno' as const,
      userId: 'st02',
      userName: 'Beatriz Silva',
      loanDate: '2026-03-08',
      expectedReturnDate: '2026-03-22',
      status: 'Activo' as const,
      notes: 'Exemplar em perfeito estado de conservação.'
    }
  ],
  hrContracts: [
    {
      id: 'ctr-001',
      employeeId: 'CAL-102938475',
      employeeName: 'Carlos Alberto Langa',
      schoolId: 's1',
      contractType: 'Nomeação Definitiva' as const,
      startDate: '2010-02-01',
      salaryGrade: 'Docente N1 - Escalão 3',
      status: 'Activo' as const,
      position: 'Professor de Matemática e Delegado de Disciplina'
    },
    {
      id: 'ctr-002',
      employeeId: 'ABM-201948392',
      employeeName: 'Ana Beatriz Machava',
      schoolId: 's1',
      contractType: 'Nomeação Definitiva' as const,
      startDate: '2008-06-15',
      salaryGrade: 'Técnico Superior N1 - Escalão 4',
      status: 'Activo' as const,
      position: 'Chefe da Secretaria Geral'
    }
  ],
  hrLeaves: [
    {
      id: 'lv-001',
      employeeId: 'CAL-102938475',
      employeeName: 'Carlos Alberto Langa',
      schoolId: 's1',
      type: 'Férias' as const,
      startDate: '2026-07-01',
      endDate: '2026-07-30',
      totalDays: 30,
      status: 'Aprovada' as const,
      approvedBy: 'Dr. Manuel Mabote',
      reason: 'Plano Anual de Férias do Corpo Docente'
    },
    {
      id: 'lv-002',
      employeeId: 'ABM-201948392',
      employeeName: 'Ana Beatriz Machava',
      schoolId: 's1',
      type: 'Formação' as const,
      startDate: '2026-04-10',
      endDate: '2026-04-14',
      totalDays: 5,
      status: 'Aprovada' as const,
      approvedBy: 'Dr. Manuel Mabote',
      reason: 'Seminário Nacional de Capacitação em Gestão Escolar (MINEDH)'
    }
  ],
  hrPromotions: [
    {
      id: 'prm-001',
      employeeId: 'CAL-102938475',
      employeeName: 'Carlos Alberto Langa',
      schoolId: 's1',
      previousCategory: 'Docente N2 - Escalão 2',
      newCategory: 'Docente N1 - Escalão 3',
      date: '2023-01-15',
      officialBulletinNumber: 'BR I Série Nº 12/2023',
      approvedBy: 'Direcção Provincial de Educação'
    }
  ],
  hrTrainings: [
    {
      id: 'trn-001',
      employeeId: 'CAL-102938475',
      employeeName: 'Carlos Alberto Langa',
      schoolId: 's1',
      courseTitle: 'Metodologias Activas e Ensino STEAM na Sala de Aula',
      institution: 'Universidade Pedagógica de Maputo',
      hours: 60,
      completionDate: '2025-11-20',
      certificateStatus: 'Concluído' as const
    }
  ],
  receptionVisitors: [
    {
      id: 'vst-001',
      schoolId: 's1',
      visitorName: 'Fernando Macamo',
      idCard: '11029838291M',
      phone: '+258 84 112 3344',
      reason: 'Matrículas/Secretaria' as const,
      departmentTarget: 'Secretaria Geral - Atendimento',
      entryTime: '08:30',
      status: 'Concluído' as const,
      attendantName: 'Laura Nhantumbo',
      notes: 'Solicitação de 2ª via de caderneta escolar do educando Afonso.'
    },
    {
      id: 'vst-002',
      schoolId: 's1',
      visitorName: 'Marta Buque',
      idCard: '11038472910F',
      phone: '+258 82 445 6677',
      reason: 'Reunião com Direcção' as const,
      departmentTarget: 'Gabinete do Director',
      entryTime: '10:15',
      status: 'Em Atendimento' as const,
      attendantName: 'Laura Nhantumbo',
      notes: 'Representante da Associação de Pais e Encarregados de Educação.'
    }
  ],
  receptionTickets: [
    {
      id: 'tkt-001',
      schoolId: 's1',
      ticketNumber: 'A-01',
      serviceType: 'Secretaria Geral' as const,
      requestedAt: '08:15',
      calledAt: '08:20',
      completedAt: '08:35',
      status: 'done' as const
    },
    {
      id: 'tkt-002',
      schoolId: 's1',
      ticketNumber: 'T-01',
      serviceType: 'Tesouraria' as const,
      requestedAt: '08:45',
      calledAt: '08:50',
      status: 'in_service' as const
    },
    {
      id: 'tkt-003',
      schoolId: 's1',
      ticketNumber: 'M-01',
      serviceType: 'Matrículas' as const,
      requestedAt: '09:00',
      status: 'waiting' as const
    }
  ],
  archiveRecords: [
    {
      id: 'arc-001',
      schoolId: 's1',
      code: 'ARC-PI-2024-001',
      title: 'Processo Individual - Afonso Matsinhe (Matrícula 2024)',
      recordType: 'Processo Individual de Aluno' as const,
      year: 2024,
      boxNumber: 'Caixa 12-A',
      shelfNumber: 'Prateleira 03',
      roomNumber: 'Sala de Arquivo Geral 1',
      status: 'Arquivado' as const,
      notes: 'Contém Certidão de Nascimento, Certificado de 9ª Classe e Ficha Médica.'
    },
    {
      id: 'arc-002',
      schoolId: 's1',
      code: 'ARC-LT-2025-10',
      title: 'Livro de Termos de Exames Finais - 10ª Classe (Ano 2025)',
      recordType: 'Livro de Termos de Exames' as const,
      year: 2025,
      boxNumber: 'Caixa 04-T',
      shelfNumber: 'Prateleira 01',
      roomNumber: 'Sala de Arquivo Geral 1',
      status: 'Arquivado' as const,
      notes: 'Assinado pelo Presidente do Júri de Exames e Director da Escola.'
    },
    {
      id: 'arc-003',
      schoolId: 's1',
      code: 'ARC-LM-2026-01',
      title: 'Livro Oficial de Registo de Matrículas e Inscrições (Ano 2026)',
      recordType: 'Livro de Matrículas' as const,
      year: 2026,
      boxNumber: 'Caixa 01-M',
      shelfNumber: 'Prateleira 01',
      roomNumber: 'Sala de Arquivo Geral 1',
      status: 'Em Consulta' as const,
      notes: 'Em utilização no período corrente de matrículas.'
    }
  ],
  classSchedules: [
    {
      id: 'sch-001',
      schoolId: 's1',
      classId: 'c1',
      className: '10ª Classe Turma A',
      dayOfWeek: 'Segunda-feira' as const,
      timeSlot: '07:00 - 08:30',
      subjectId: 'sub4',
      subjectName: 'Português',
      teacherId: 'u4',
      teacherName: 'Prof. João Professor',
      room: 'Sala 01 - Bloco A'
    },
    {
      id: 'sch-002',
      schoolId: 's1',
      classId: 'c1',
      className: '10ª Classe Turma A',
      dayOfWeek: 'Segunda-feira' as const,
      timeSlot: '08:45 - 10:15',
      subjectId: 'sub1',
      subjectName: 'Matemática',
      teacherId: 'u4',
      teacherName: 'Prof. Carlos Langa',
      room: 'Sala 01 - Bloco A'
    },
    {
      id: 'sch-003',
      schoolId: 's1',
      classId: 'c1',
      className: '10ª Classe Turma A',
      dayOfWeek: 'Terça-feira' as const,
      timeSlot: '07:00 - 08:30',
      subjectId: 'sub2',
      subjectName: 'Física',
      teacherId: 'u4',
      teacherName: 'Prof. João Professor',
      room: 'Laboratório de Física'
    },
    {
      id: 'sch-004',
      schoolId: 's1',
      classId: 'c1',
      className: '10ª Classe Turma A',
      dayOfWeek: 'Quarta-feira' as const,
      timeSlot: '10:30 - 12:00',
      subjectId: 'sub3',
      subjectName: 'Química',
      teacherId: 'u4',
      teacherName: 'Prof. João Professor',
      room: 'Laboratório de Química'
    },
    {
      id: 'sch-005',
      schoolId: 's1',
      classId: 'c1',
      className: '10ª Classe Turma A',
      dayOfWeek: 'Quinta-feira' as const,
      timeSlot: '07:00 - 08:30',
      subjectId: 'sub9',
      subjectName: 'Biologia',
      teacherId: 'u4',
      teacherName: 'Profa. Sofia Langa',
      room: 'Sala 01 - Bloco A'
    }
  ],
  schoolRooms: [
    { id: 'rm-01', schoolId: 's1', name: 'Sala 01 - Bloco A', capacity: 45, type: 'Sala Normal' as const, status: 'Ocupada' as const },
    { id: 'rm-02', schoolId: 's1', name: 'Sala 02 - Bloco A', capacity: 45, type: 'Sala Normal' as const, status: 'Disponível' as const },
    { id: 'rm-03', schoolId: 's1', name: 'Laboratório de Informática 1', capacity: 35, type: 'Laboratório de Informática' as const, status: 'Ocupada' as const },
    { id: 'rm-04', schoolId: 's1', name: 'Laboratório de Ciências e Biologia', capacity: 30, type: 'Laboratório de Ciências' as const, status: 'Disponível' as const },
    { id: 'rm-05', schoolId: 's1', name: 'Biblioteca Central Josina Machel', capacity: 80, type: 'Biblioteca' as const, status: 'Disponível' as const },
    { id: 'rm-06', schoolId: 's1', name: 'Polidesportivo / Campo Coberto', capacity: 200, type: 'Ginásio/Polidesportivo' as const, status: 'Disponível' as const }
  ],
  aiPredictions: [
    {
      studentId: 'st10',
      studentName: 'Fátima Nhaca',
      classId: 'c1',
      className: '10ª Classe Turma A',
      dropOutRiskScore: 78,
      riskLevel: 'Alto' as const,
      riskFactors: ['Média abaixo de 9.0 valores (Matemática e Física)', 'Assiduidade com 14 faltas não justificadas no 1º Trimestre', 'Falta de material didático essencial'],
      recommendedInterventions: ['Convocatória do Encarregado de Educação para tutoria', 'Inscrição no programa de apoio pedagógico aos sábados', 'Acompanhamento pela Comissão de Apoio Social'],
      predictedFinalAverage: 8.4,
      attendanceRate: 72,
      generatedAt: '2026-03-20T08:00:00Z'
    },
    {
      studentId: 'st30',
      studentName: 'Tomás Langa',
      classId: 'c2',
      className: '10ª Classe Turma B',
      dropOutRiskScore: 65,
      riskLevel: 'Médio' as const,
      riskFactors: ['Oscilação acentuada nas notas de Química e Biologia', 'Atrasos frequentes no período da tarde'],
      recommendedInterventions: ['Sessão de orientação com o Coordenador de Ciclo', 'Revisão do horário de apoio'],
      predictedFinalAverage: 9.2,
      attendanceRate: 81,
      generatedAt: '2026-03-20T08:00:00Z'
    },
    {
      studentId: 'st01',
      studentName: 'Afonso Matsinhe',
      classId: 'c1',
      className: '10ª Classe Turma A',
      dropOutRiskScore: 4,
      riskLevel: 'Baixo' as const,
      riskFactors: ['Nenhum factor de risco identificado. Alto rendimento escolar.'],
      recommendedInterventions: ['Indicação para as Olimpíadas Nacionais de Matemática', 'Apoio a colegas como monitor de turma'],
      predictedFinalAverage: 16.2,
      attendanceRate: 98,
      generatedAt: '2026-03-20T08:00:00Z'
    }
  ],
  aiReports: [
    {
      id: 'air-001',
      schoolId: 's1',
      title: 'Diagnóstico Pedagógico e Preditivo do 1º Trimestre 2026',
      category: 'Desempenho Pedagógico' as const,
      content: 'A análise preditiva do EduGestão IA identificou uma taxa global de aprovação projectada de 87.4% para as turmas do Diurno. As disciplinas de Matemática e Física apresentam a maior necessidade de reforço pedagógico...',
      generatedAt: '2026-03-21T14:30:00Z',
      author: 'EduGestão AI Engine v4.2'
    }
  ]
};

